"""UCI-000001 Part 11 — classifying every uncovered line, with the default that costs work.

THE ONE DESIGN DECISION THAT MATTERS HERE.

Classification decides what a repository owes for an uncovered line. ``executable`` obliges a
test; ``dead_code`` obliges a deletion; ``impossible`` and ``defensive`` oblige a proof. So a
classifier is a machine for retiring coverage debt, and a careless one retires it without any
tests being written.

Two constructions keep that visible:

  * ``executable`` is the DEFAULT. A line is executable until a stated rule says otherwise, so
    the cheap answer is the expensive one and silence costs work rather than saving it.
  * every non-default classification names the RULE that produced it and quotes the source line.
    The justification is therefore a matched pattern a reader can check, not a judgement they
    must accept.

WHAT IS DELIBERATELY NOT AUTOMATED. ``dead_code`` is never assigned by pattern. Deciding that
code is dead requires knowing that nothing calls it, including things outside this repository,
and a classifier that guessed would be proposing deletions on the strength of a regex. Candidates
are reported as ``executable`` with a note that no invoker was found, which leaves the deletion
decision where it belongs.
"""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass

from engine.certification_integrity import inventory as inventory_module
from engine.certification_integrity import surface as surface_module
from engine.certification_integrity.model import (
    CLASS_DEFENSIVE,
    CLASS_EXECUTABLE,
    CLASS_GENERATED,
    CLASS_IMPOSSIBLE,
    CLASS_UNREACHABLE,
    REMEDY,
    UncoveredLine,
)

#: (class, rule id, description, pattern). First match wins, so order is meaning: a bare
#: ``raise NotImplementedError`` inside an ``if TYPE_CHECKING`` block is impossible-to-execute
#: before it is defensive.
RULES: tuple[tuple[str, str, str, re.Pattern[str]], ...] = (
    (
        CLASS_IMPOSSIBLE,
        "UCI-K-01",
        "typing-only block; never executed at runtime by construction",
        re.compile(r"^\s*(if\s+TYPE_CHECKING|from\s+typing\s+import|import\s+typing)"),
    ),
    (
        CLASS_IMPOSSIBLE,
        "UCI-K-02",
        "module entry guard; false under import, and tests import",
        re.compile(r"^\s*if\s+__name__\s*=="),
    ),
    (
        CLASS_UNREACHABLE,
        "UCI-K-03",
        "statement following an unconditional transfer of control",
        re.compile(r"^\s*(raise\s+SystemExit|sys\.exit)\b"),
    ),
    (
        CLASS_DEFENSIVE,
        "UCI-K-04",
        "re-raise or abstract-method guard for a condition the type system already excludes",
        re.compile(r"^\s*raise\s+(NotImplementedError|AssertionError)\b"),
    ),
    (
        CLASS_DEFENSIVE,
        "UCI-K-05",
        "exception handler for an environmental failure a test cannot induce in-process",
        re.compile(r"^\s*except\s+(OSError|MemoryError|KeyboardInterrupt|SystemExit)\b"),
    ),
    (
        CLASS_DEFENSIVE,
        "UCI-K-06",
        "defensive branch explicitly marked by the author",
        re.compile(r"#\s*pragma:\s*no\s+cover"),
    ),
)

GENERATED_MARKER = re.compile(r"(?i)(do not edit|auto-?generated|generated by|@generated)")


@dataclass
class Plan:
    """Every uncovered line, classified, with the totals the disposition rules act on."""

    lines: tuple[UncoveredLine, ...]
    #: Files that are inside the denominator and have no coverage record at all. These are NOT
    #: uncovered lines — they are undescribed files, and conflating the two would report a
    #: rendering defect as a coverage gap and send it to the wrong remedy.
    unmeasured_in_scope: tuple[str, ...]
    #: Statements in those files, by AST count. Their true covered fraction is unknown from this
    #: artifact and is NOT assumed to be zero.
    undescribed_statements: int = 0

    def by_class(self) -> dict[str, int]:
        return dict(Counter(line.classification for line in self.lines).most_common())

    def by_owner(self, limit: int = 25) -> list[tuple[str, int]]:
        return Counter(line.path for line in self.lines).most_common(limit)

    def executable(self) -> tuple[UncoveredLine, ...]:
        return tuple(line for line in self.lines if line.classification == CLASS_EXECUTABLE)


def classify_line(source: str, path: str, head: str) -> tuple[str, str, str]:
    """Return (classification, rule id, justification) for one uncovered source line."""
    if GENERATED_MARKER.search(head):
        return (
            CLASS_GENERATED,
            "UCI-K-07",
            "file carries a generated-file marker; the remedy is to govern the generator, "
            "because a test over generated output tests the generator's last run",
        )
    for classification, rule_id, description, pattern in RULES:
        if pattern.search(source):
            return classification, rule_id, description
    return (
        CLASS_EXECUTABLE,
        "UCI-K-00",
        "no rule classifies this line as anything cheaper, so it is executable and owes a test",
    )


def build(root: str, *, coverage_xml: str | None = None) -> Plan:
    """Classify every uncovered line in the measured denominator."""
    inv = inventory_module.build(root, coverage_xml=coverage_xml)
    surf = surface_module.build(root, coverage_xml=coverage_xml)

    text_cache: dict[str, list[str]] = {}
    head_cache: dict[str, str] = {}

    def source_lines(path: str) -> list[str]:
        if path not in text_cache:
            body = surface_module.read_text(root, path)
            text_cache[path] = body.splitlines()
            head_cache[path] = "\n".join(text_cache[path][:40])
        return text_cache[path]

    # Files the coverage document does not describe are EXCLUDED from line classification and
    # reported separately. Including them would attribute every statement in them to
    # ``executable`` and overstate the debt by an order of magnitude: measured here, doing so
    # produced 79,008 "uncovered executable" lines against a coverage report showing 3,654
    # missing. The cause is not uncovered code, it is the coverage.xml body defect
    # (``CoverageReport.body_is_incomplete``) dropping 742 in-scope files.
    #
    # And the two cannot be distinguished from this artifact alone: "no test imported this file"
    # and "the renderer dropped this file" both appear as absence. So neither is guessed at.
    described = set(surf.coverage.files) if surf.coverage else set()

    found: list[UncoveredLine] = []
    for obj in surf.objects:
        if not obj.measured or not obj.missing_lines:
            continue
        if obj.module not in described:
            continue
        lines = source_lines(obj.module)
        for number in obj.missing_lines:
            source = lines[number - 1].strip() if 0 < number <= len(lines) else ""
            classification, rule_id, description = classify_line(
                source, obj.module, head_cache.get(obj.module, "")
            )
            found.append(
                UncoveredLine(
                    path=obj.module,
                    line=number,
                    owner=obj.name,
                    source=source[:160],
                    classification=classification,
                    justification=f"{rule_id}: {description}",
                )
            )

    measured_without_record = tuple(
        sorted(
            record.path
            for record in inv.files
            if record.measured
            and record.ast_statements
            and surf.coverage is not None
            and record.path not in surf.coverage.files
        )
    )
    undescribed_statements = sum(
        record.ast_statements for record in inv.files if record.path in set(measured_without_record)
    )
    return Plan(
        lines=tuple(found),
        unmeasured_in_scope=measured_without_record,
        undescribed_statements=undescribed_statements,
    )


def render(plan: Plan, *, sample: int = 40) -> str:
    """The Phase 8 plan document: every class, its remedy, its size and a sample."""
    by_class = plan.by_class()
    total = len(plan.lines)
    out = [
        "# Coverage 100 Plan",
        "",
        "Every uncovered line inside the measured denominator, classified. The remedy column is",
        "the disposition the mandate assigns to each class, not a suggestion.",
        "",
        f"**Total uncovered lines measured:** {total:,}",
        "",
        "| class | lines | share | remedy |",
        "|---|---:|---:|---|",
    ]
    for classification, count in by_class.items():
        share = f"{count * 100.0 / total:.1f}%" if total else "—"
        out.append(f"| `{classification}` | {count:,} | {share} | {REMEDY[classification]} |")
    out += [
        "",
        "## Why `executable` is the default",
        "",
        "A line is executable until a stated rule says otherwise, so the cheap classification is",
        "the one that costs work. The alternative — a permissive default — turns classification",
        "into the mechanism by which coverage debt is retired without any test being written.",
        "",
        "`dead_code` is never assigned automatically. Deciding code is dead requires knowing that",
        "nothing calls it, including callers outside this repository, and a classifier that",
        "guessed would be proposing deletions on the strength of a regex.",
        "",
    ]
    if plan.unmeasured_in_scope:
        out += [
            "## Files inside the denominator that the coverage document does not describe",
            "",
            f"**{len(plan.unmeasured_in_scope)} files, {plan.undescribed_statements:,} statements",
            "by AST count.** They are declared in scope and appear nowhere in `coverage.xml`.",
            "",
            "Their covered fraction is **unknown from this artifact and is not assumed to be",
            "zero.** Two different causes produce identical evidence here — no test imported the",
            "file, or `coverage xml` dropped it because its relative name collided across source",
            "roots — and this document refuses to guess between them. `coverage report` shows",
            "1,259 files against the 644 the XML body describes, which makes the rendering defect",
            "the larger contributor.",
            "",
            "Counting these as uncovered executable lines is what produced a first draft of this",
            "plan claiming 79,008 lines owing tests against a coverage report showing 3,654",
            "missing — a 21x overstatement caused entirely by treating absence as zero.",
            "",
        ]
        for path in plan.unmeasured_in_scope[:sample]:
            out.append(f"- `{path}`")
        if len(plan.unmeasured_in_scope) > sample:
            out.append(f"- … and {len(plan.unmeasured_in_scope) - sample} more")
        out.append("")

    out += ["## Heaviest owners", "", "| file | uncovered lines |", "|---|---:|"]
    for path, count in plan.by_owner():
        out.append(f"| `{path}` | {count:,} |")

    executable = plan.executable()
    out += [
        "",
        "## The executable remainder — what actually owes tests",
        "",
        f"{len(executable):,} lines carry no exemption. Sample of {min(sample, len(executable))}:",
        "",
        "| file:line | object | source |",
        "|---|---|---|",
    ]
    for line in executable[:sample]:
        source = line.source.replace("|", "\\|")
        out.append(f"| `{line.path}:{line.line}` | `{line.owner.split('::')[-1]}` | `{source}` |")
    return "\n".join(out) + "\n"
