"""UCI-000001 Part 4 — the authoritative executable inventory (mandate Rule 2).

WHAT THIS FILE IS FOR.

Rule 2 requires that every tracked Python artifact be classified and that no executable artifact
remain outside the measured denominator. Both halves need one population, computed once. Before
this module the repository had three populations that were never compared: what ``--cov=``
measures, what ``git ls-files`` contains, and what UEC-000001 governs. A file could sit in
exactly one of them indefinitely, and 619 files did.

THE CLASSIFICATION IS A CLAIM, AND IS RECORDED AS ONE.

``classification`` decides whether a file's absence from the denominator is a defect or a
governed exclusion, which makes it the single most abusable field in this package: reclassifying
``executable`` as ``archived`` would retire coverage debt without writing a test. Three
constructions make that visible rather than easy:

  * the DEFAULT is ``executable``. Nothing falls into a cheaper class by omission.
  * every non-``executable`` classification records the RULE that produced it, so the reason is
    a matched pattern rather than a judgement, and a reader can check it.
  * ``intentionally_excluded`` is the only class that can be asserted by hand, it can only be
    asserted in ``[tool.ucos.coverage_scope]``, and ``platform/tests/test_coverage_scope.py``
    already refuses an entry there that is stale in either direction.

``governing_authority`` answers the separate question Rule 3 asks: not "is this measured" but
"does anything anywhere claim this file". A file measured by coverage and governed by nothing is
still a Rule 3 finding, because coverage measures execution and not existence.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
from dataclasses import dataclass

from engine.certification_integrity import surface as surface_module
from engine.certification_integrity.model import (
    FILE_ARCHIVED,
    FILE_EXCLUDED,
    FILE_EXECUTABLE,
    FILE_GENERATED,
    FILE_MIGRATION,
    FILE_TEST,
    FILE_TOOLING,
    KIND_CLASS,
    KIND_FUNCTION,
    KIND_METHOD,
    FileRecord,
)

SCHEMA = "ucos-coverage-gap-inventory"
VERSION = "1.0.0"

#: Ordered classification rules. FIRST MATCH WINS and the order is load-bearing: ``test`` is
#: tried before ``tooling`` so a test helper under a tools directory is a test, and ``archived``
#: is tried before ``executable`` so a frozen tree is not reported as live debt. Each entry is
#: (rule id, classification, predicate description, compiled pattern over the POSIX path).
CLASSIFICATION_RULES: tuple[tuple[str, str, str, re.Pattern[str]], ...] = (
    (
        "UCI-C-01",
        FILE_ARCHIVED,
        "under a frozen or archived tree, which DP-03 forbids writing to",
        re.compile(r"^(\.archive/|99-FREEZE/|00-SOURCE/|dist/)"),
    ),
    (
        "UCI-C-02",
        FILE_GENERATED,
        "carries a generated-file marker in its first 40 lines",
        re.compile(r"^$"),  # matched by content, not path; see _classify
    ),
    (
        "UCI-C-03",
        FILE_MIGRATION,
        "a one-shot migration or backfill script",
        re.compile(r"(^|/)(migrat|backfill|one_shot|oneshot)[^/]*\.py$"),
    ),
    (
        "UCI-C-04",
        FILE_TOOLING,
        "repository tooling outside the engine/platform source trees",
        re.compile(r"^(00-BOOK/tools/|scripts/|00-CMG/tools/)"),
    ),
)

GENERATED_MARKER = re.compile(
    r"(?i)(do not edit|auto-?generated|generated by|@generated|machine.generated)"
)


@dataclass(frozen=True)
class Inventory:
    """The whole inventory, plus the Rule 2 and Rule 3 findings derived from it."""

    files: tuple[FileRecord, ...]
    objects: tuple[dict[str, object], ...]
    totals: dict[str, object]
    #: Rule 2's refusal condition: executable artifacts outside the measured denominator.
    executable_outside_denominator: tuple[str, ...]
    #: Rule 3's refusal condition: files that exist in exactly one of the four surfaces.
    ungoverned_files: tuple[str, ...]
    scope_drift: dict[str, object]

    def digest(self) -> str:
        """Content hash over the inventory, for the Rule 7 provenance record."""
        payload = {
            "files": [f.as_record() for f in self.files],
            "totals": self.totals,
        }
        encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
        return hashlib.sha256(encoded).hexdigest()

    def as_document(self) -> dict[str, object]:
        return {
            "schema": SCHEMA,
            "version": VERSION,
            "authority": "NONE — DERIVED TRUTH. Measurement of tracked repository state.",
            "producer": "engine/certification_integrity/inventory.py",
            "determinism": (
                "No wall clock, no commit identity, no working-tree status. The bytes are a "
                "pure function of tracked content, so two runs over one tree are identical."
            ),
            "totals": self.totals,
            "findings": {
                "executable_outside_denominator": list(self.executable_outside_denominator),
                "ungoverned_files": list(self.ungoverned_files),
                "scope_drift": self.scope_drift,
            },
            "files": [f.as_record() for f in self.files],
            "objects": list(self.objects),
        }


def _classify(
    path: str, text: str, excluded_packages: dict[str, str], is_test: bool
) -> tuple[
    str,
    str,
    str | None,
]:
    """Return (classification, rule id, exclusion reason).

    ``executable`` is the default and carries rule id ``UCI-C-00``, which is the absence of a
    reason to classify it as anything cheaper.
    """
    if is_test:
        return FILE_TEST, "UCI-C-05", None
    dotted = surface_module.module_dotted(path)
    for package, reason in excluded_packages.items():
        if dotted == package or dotted.startswith(package + "."):
            return FILE_EXCLUDED, "UCI-C-06", reason
    head = "\n".join(text.splitlines()[:40])
    for rule_id, classification, _description, pattern in CLASSIFICATION_RULES:
        if classification is FILE_GENERATED:
            if GENERATED_MARKER.search(head):
                return FILE_GENERATED, rule_id, None
            continue
        if pattern.search(path):
            return classification, rule_id, None
    return FILE_EXECUTABLE, "UCI-C-00", None


def build(root: str, *, coverage_xml: str | None = None) -> Inventory:
    """Enumerate, classify and join. One population, computed once."""
    surf = surface_module.build(root, coverage_xml=coverage_xml)
    scope = surf.scope

    by_module: dict[str, list] = {}
    for obj in surf.objects:
        by_module.setdefault(obj.module, []).append(obj)

    tracked_python = sorted(set(surf.measured_files) | set(surf.unmeasured_files))
    records: list[FileRecord] = []
    for path in tracked_python:
        text = surface_module.read_text(root, path)
        classification, rule_id, exclusion = _classify(
            path, text, dict(scope.excluded_packages), scope.is_test(path)
        )
        objects = by_module.get(path, [])
        statements = sum(o.statements for o in objects)
        ast_statements = _ast_statements(text)
        covered = sum(o.covered for o in objects)
        measured = scope.measures(path)
        # Execution paths: the callable entry points inside the file. A module with 40 functions
        # has 40 ways to be entered, and "the file is 90% covered" says nothing about how many of
        # them ran, which is why this is recorded per file rather than inferred from a ratio.
        #
        # Derived from the AST structure ALONE, never from statement counts. Statement counts are
        # intersected with the coverage report when one is present, so filtering on them would make
        # this field — and UCI-L-06, which reads it — answer differently depending on whether
        # coverage.xml happened to exist. A law whose verdict depends on the presence of an
        # artifact it does not measure is not a law about the repository.
        execution_paths = tuple(
            sorted(o.name for o in objects if o.kind in (KIND_FUNCTION, KIND_METHOD, KIND_CLASS))
        )
        planes: set[str] = set()
        for obj in objects:
            planes.update(obj.invocation_planes)
        records.append(
            FileRecord(
                path=path,
                classification=classification,
                statements=statements,
                covered=covered,
                missing=statements - covered,
                measured=measured,
                execution_paths=execution_paths,
                invocation_sources=tuple(sorted(planes)),
                governing_authority=_authority(path, measured, classification, rule_id),
                exclusion_reason=exclusion,
                ast_statements=ast_statements,
            )
        )

    executable_outside = tuple(
        r.path
        for r in records
        if r.classification in (FILE_EXECUTABLE, FILE_TOOLING) and not r.measured
    )
    ungoverned = tuple(r.path for r in records if r.governing_authority.startswith("NONE"))

    totals = dict(surf.totals())
    totals["by_classification"] = {
        classification: {
            "files": sum(1 for r in records if r.classification == classification),
            "statements": sum(r.statements for r in records if r.classification == classification),
            "measured_files": sum(
                1 for r in records if r.classification == classification and r.measured
            ),
        }
        for classification in sorted({r.classification for r in records})
    }
    totals["engines"] = len(surf.engines)
    totals["verify_stages"] = len(surf.stages)

    return Inventory(
        files=tuple(records),
        objects=tuple(o.as_record() for o in surf.objects),
        totals=totals,
        executable_outside_denominator=executable_outside,
        ungoverned_files=ungoverned,
        scope_drift=_scope_drift(scope, surf),
    )


def _ast_statements(text: str) -> int:
    """Statement count from the source alone. Independent of any coverage measurement."""
    import ast

    try:
        tree = ast.parse(text)
    except SyntaxError:
        return 0
    return len({node.lineno for node in ast.walk(tree) if isinstance(node, ast.stmt)})


def _authority(path: str, measured: bool, classification: str, rule_id: str) -> str:
    """Who claims this file. ``NONE`` is a finding, not a default to be tolerated."""
    if surface_module.is_engine(path):
        return "UEC-000001 (enforcement closure inventory)"
    if classification == FILE_EXCLUDED:
        return "UCOS-COV-SCOPE-001 (declared exclusion, reason recorded)"
    if classification == FILE_TEST:
        return "UCOS-COV-SCOPE-001 (omit list); pytest testpaths"
    if classification == FILE_ARCHIVED:
        return "DP-03 frozen-path guard"
    if measured:
        return "UCOS-COV-SCOPE-001 (coverage denominator)"
    return f"NONE — no authority claims this file (classified {classification} by {rule_id})"


def _scope_drift(scope: surface_module.Scope, surf: surface_module.Surface) -> dict[str, object]:
    """Rule 3: the four surfaces, and every file that is in exactly one of them.

    Coverage scope, executable surface, governed surface and discovery surface are computed
    independently and then compared. The comparison is the product: three of these were already
    computable and no code had ever asked whether they agreed.
    """
    coverage_surface = set(surf.measured_files)
    executable_surface = set(surf.measured_files) | set(surf.unmeasured_files)
    governed_surface = set(surf.engines)
    discovery_surface = {
        path for path in executable_surface if not path.startswith(("00-MASTER/", ".archive/"))
    }
    return {
        "coverage_scope": len(coverage_surface),
        "executable_surface": len(executable_surface),
        "governed_surface": len(governed_surface),
        "discovery_surface": len(discovery_surface),
        "executable_not_in_coverage_scope": len(executable_surface - coverage_surface),
        "governed_not_in_coverage_scope": sorted(governed_surface - coverage_surface),
        "coverage_scope_not_executable": sorted(coverage_surface - executable_surface),
    }


def write(root: str, destination: str, *, coverage_xml: str | None = None) -> Inventory:
    """Render the inventory to disk.

    This is the ONE place in the package that writes, and it writes only when a caller names a
    destination. It writes no expectation: nothing in this package reads
    ``coverage_gap_inventory.json`` back to decide whether a law holds, so regenerating it can
    never turn a refusal into a pass.
    """
    inventory = build(root, coverage_xml=coverage_xml)
    document = inventory.as_document()
    os.makedirs(os.path.dirname(os.path.abspath(destination)) or ".", exist_ok=True)
    with open(destination, "w", encoding="utf-8") as handle:
        json.dump(document, handle, indent=1, sort_keys=True)
        handle.write("\n")
    return inventory
