"""UCOS-OMEGA-001 Part 5 (Ω-5) — one disposition per artifact, and no sixth possibility.

THE GAP THIS CLOSES. 82.07% of the executable surface was inside a measured denominator and
17.93% was outside it with nothing anywhere stating why. "Outside" was not a classification, it
was an absence — 28,105 statements whose governance status was the empty string. An absence
cannot be ratcheted, cannot be reported and cannot be argued with.

Ω-5 abolishes the absence. Every tracked Python artifact receives exactly one of five
dispositions, and the last rule is unconditional, so the terminal states "unknown", "orphan" and
"authority-free" are unreachable by construction rather than merely unobserved.

THE RULES CLASSIFY BY MEASURED PROPERTY. Never by location, never by naming, never by a directory
somebody typed. Each rule below states the property it measures and the mechanism that measures
it, and each records its rule id onto the artifact so a reader can check the claim rather than
trust it:

  Ω-C-01  TRANSIENT   the owner declared it transient, with a reason. The one human assertion.
  Ω-C-02  ARCHIVED    the DP-03 frozen-path guard already refuses writes to it. Read from the
                      guard, so the disposition tracks the guard and cannot drift from it.
  Ω-C-03  GENERATED   its own first lines say a producer owns its bytes. Content, not path.
  Ω-C-04  MEASURED    a measurement runs over it: coverage names its package, or it is a module
                      of a discovered suite and the suite executes it.
  Ω-C-05  EXEMPTED    an owner declared its package outside the denominator, with a reason.
  Ω-C-06  EXEMPTED    its root is not a Python identifier, so NO coverage source could name it.
                      This is the honest disposition of the 39 governance engines: they are
                      invoked by gates, workflows and ``verify.sh``, they are owned, and they
                      cannot enter a coverage denominator because ``00-MASTER`` is not a module
                      name. Measured from the language's own rule for identifiers.
  Ω-C-07  EXEMPTED    unconditional. Outside measurement for a reason this run could not derive,
                      which is a FINDING with a name — and the population of this rule is the
                      convergent ratchet that makes it shrink.

Ω-C-07 IS THE DESIGN'S HONESTY. A totalising classifier is worthless if its last rule is
comfortable, so the last rule is the one that hurts: everything the earlier rules could not
explain lands in a single named bucket whose size is ratcheted convergently and reported first.
It may fall and hold. It may never rise.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence

from engine.universal_discovery.discovery import is_importable_name, module_dotted
from engine.universal_discovery.model import (
    ARCHIVED,
    EXEMPTED,
    GENERATED,
    MEASURED,
    TRANSIENT,
)

RULE_TRANSIENT = "Ω-C-01"
RULE_ARCHIVED = "Ω-C-02"
RULE_GENERATED = "Ω-C-03"
RULE_MEASURED = "Ω-C-04"
RULE_DECLARED_EXEMPT = "Ω-C-05"
RULE_UNNAMEABLE = "Ω-C-06"
RULE_UNEXPLAINED = "Ω-C-07"

#: The producer marker, matched against the artifact's own first lines. Content-keyed, so a
#: generated file is generated wherever it is written and a hand-authored file cannot become
#: generated by being moved.
GENERATED_MARKER = re.compile(
    r"(?i)(do not edit|auto-?generated|generated by|@generated|machine.generated)"
)
MARKER_WINDOW = 40


def _generated_marker(source: str) -> bool:
    """Whether a producer marker appears in the artifact's first ``MARKER_WINDOW`` lines.

    THE WINDOW IS ENFORCED HERE, not by the caller, and that placement was a defect until it was
    tested. ``surface.build`` already truncates for memory, so the bound looked enforced — but any
    other caller passing a whole file would have had a passing mention of "do not edit" hundreds of
    lines down retire the artifact's obligation. A bound belongs where it is declared.
    """
    return bool(GENERATED_MARKER.search("\n".join(source.splitlines()[:MARKER_WINDOW])))


#: Rules that produce EXEMPTED. Named as a population because each one's size is a convergent
#: ratchet: an exemption class that stops shrinking must be visible as a stalled measurement
#: rather than invisible as a settled convention.
EXEMPTION_RULES: tuple[str, ...] = (RULE_DECLARED_EXEMPT, RULE_UNNAMEABLE, RULE_UNEXPLAINED)


def _under_any(path: str, prefixes: Sequence[str]) -> bool:
    return any(path == p.rstrip("/") or path.startswith(p.rstrip("/") + "/") for p in prefixes)


def _measured_by_coverage(path: str, packages: Sequence[str]) -> bool:
    """Whether the derived coverage denominator names this artifact's package.

    Asked of the DOTTED MODULE, never of the path, which is what makes the answer survive a
    relocation: ``engine.foundation.identity`` is the same subject whatever directory holds it.
    """
    dotted = module_dotted(path)
    if not dotted:
        return False
    return any(dotted == package or dotted.startswith(package + ".") for package in packages)


def classify(
    path: str,
    *,
    source_head: str,
    measurable_packages: Sequence[str],
    test_roots: Sequence[str],
    frozen: Sequence[str],
    declared_exemptions: Mapping[str, str],
    declared_transient: Mapping[str, str],
) -> tuple[str, str, str]:
    """``(disposition, rule, reason)``. TOTAL: the final rule takes no condition.

    ORDER IS LOAD-BEARING AND THE ORDERING PRINCIPLE IS "CHEAPEST CLASS LAST". A disposition that
    retires an obligation must be harder to reach than one that keeps it, so TRANSIENT, ARCHIVED
    and GENERATED — the three that remove an artifact from the surface entirely — are all gated on
    an explicit declaration or on the artifact's own content, and never on a guess.
    """
    if path in declared_transient:
        return (
            TRANSIENT,
            RULE_TRANSIENT,
            f"declared transient by its owner: {declared_transient[path]}",
        )

    if _under_any(path, frozen):
        return (
            ARCHIVED,
            RULE_ARCHIVED,
            "inside a prefix the DP-03 frozen-path guard protects, so writing to it is already "
            "refused and measuring it would measure a state no commit can change",
        )

    if _generated_marker(source_head):
        return (
            GENERATED,
            RULE_GENERATED,
            "declares in its own first lines that a producer owns its bytes, so measuring it "
            "would measure the producer twice and reward generating more of it",
        )

    if _under_any(path, test_roots):
        return (
            MEASURED,
            RULE_MEASURED,
            "a module of a discovered suite; the suite executes it on every run, which is a "
            "measurement of it even though coverage omits it from its own denominator",
        )

    if _measured_by_coverage(path, measurable_packages):
        return (
            MEASURED,
            RULE_MEASURED,
            "the derived coverage denominator names its package",
        )

    dotted = module_dotted(path)
    for package, reason in declared_exemptions.items():
        if dotted and (dotted == package or dotted.startswith(package + ".")):
            return EXEMPTED, RULE_DECLARED_EXEMPT, f"declared exempt with a reason: {reason}"

    root = path.split("/", 1)[0] if "/" in path else ""
    if root and not is_importable_name(root):
        return (
            EXEMPTED,
            RULE_UNNAMEABLE,
            f"its root {root!r} is not a Python identifier, so no coverage source could name it; "
            "it is reached and owned through the execution graph instead",
        )
    if not dotted:
        return (
            EXEMPTED,
            RULE_UNNAMEABLE,
            "no import could name this path, so no coverage source could name it either",
        )

    return (
        EXEMPTED,
        RULE_UNEXPLAINED,
        "outside every measurement this run could derive, and no rule explains why — a FINDING, "
        "counted by the convergent ratchet that must drive this population to zero",
    )


def assert_total(dispositions: Mapping[str, tuple[str, str, str]]) -> None:
    """Ω-5's invariant, asserted: exactly one disposition each, and every one of them stated.

    Refuses BY NAME rather than reporting a coverage percentage of the classifier, because a
    classifier that is 99% total has an unknown state and an unknown state is the whole defect.
    """
    from engine.universal_discovery.model import DISPOSITIONS, OmegaError

    unknown = sorted(
        path
        for path, (disposition, rule, reason) in dispositions.items()
        if disposition not in DISPOSITIONS or not rule or not reason
    )
    if unknown:
        raise OmegaError(
            "these artifacts carry no valid disposition, so the classification is not total: "
            + ", ".join(unknown[:20])
        )
