#!/usr/bin/env python3
"""UCCEP-000005 — emit Outputs 7, 8 and 9 from the derived dependency view.

Reads ``evidence/post/dependency-derivation.json`` (produced by ``derive.py``, which
reads only the located owners) and renders it as markdown. Regenerated, never
hand-authored. AUTHORITY = NONE (DERIVED TRUTH).

    python3 00-MASTER/UCCEP-000005/emit_views.py
"""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent
SRC = OUT / "evidence" / "post" / "dependency-derivation.json"

#: The Engineering-Foundation spine in ENG-GOV-001 Output 11 Option B order.
ENG_SPINE = (
    ("UCOS-ENG-000003", "ENG-000", "Engineering Program Master Index"),
    ("UCOS-ENG-000005", "ENG-001", "Universal Identity System"),
    ("UCOS-ENG-000006", "ENG-002", "Universal Object System"),
    ("UCOS-ENG-000009", "ENG-003", "Universal Value System"),
    ("UCOS-ENG-000008", "ENG-004", "Universal Type System"),
    ("UCOS-ENG-000007", "ENG-005", "Universal Relationship & Reference System"),
)

HDR = """| Field | Value |
|---|---|
| PROGRAMME | `UCCEP-000005` · PHASE 5 (T-3 Repository Re-Derivation) |
| AUTHORITY | **NONE — DERIVED TRUTH** |
| LOCATED OWNER | {owner} |
| SOURCE | `00-BOOK/DATA/relationships.json` (`Depends-On`, artifact→artifact) |
| GENERATED BY | `00-MASTER/UCCEP-000005/emit_views.py` — regenerated, never hand-authored |
"""


def main() -> int:
    payload = json.loads(SRC.read_text())
    dep = payload["dependency"]
    con = payload["consistency"]
    groups: list[list[str]] = dep["parallel_groups"]
    path: list[str] = dep["critical_path"]

    depth_of = {n: i for i, g in enumerate(groups) for n in g}

    # ---------------------------------------------------------------- Output 7
    prog: dict[str, int] = {}
    for node in depth_of:
        family = node.split("-")[1] if node.count("-") >= 2 else "?"
        prog[family] = prog.get(family, 0) + 1

    o7 = [
        "# Output 7 — Updated Dependency Graph",
        "",
        HDR.format(owner="`engine/graph` (UCOS-EPIC-002)"),
        "",
        "---",
        "",
        "## 1. Shape",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Artifact nodes in the dependency projection | {dep['artifact_nodes']} |",
        f"| `Depends-On` edges (artifact→artifact) | {dep['depends_on_edges']} |",
        f"| Strongly-connected components | {dep['scc_total']} |",
        f"| **Components with more than one member** | **{dep['scc_gt1_count']}** |",
        f"| Self-loops | {len(dep['self_loops'])} |",
        f"| Duplicate dependency edges | {len(dep['duplicate_dependency_edges'])} |",
        f"| Malformed dependency edges | {len(dep['malformed_dependency_edges'])} |",
        f"| **Acyclic** | **{str(dep['acyclic']).upper()}** |",
        f"| Topological ordering | {dep['dependency_ordering_count']}/{dep['artifact_nodes']}"
        f" · complete = {str(dep['dependency_ordering_complete']).upper()} |",
        f"| Dependency depth (levels) | {dep['parallel_group_count']} |",
        f"| Critical-path length | {dep['critical_path_length']} |",
        "",
        "## 2. Integrity",
        "",
        "| Check | Value |",
        "|---|---|",
        f"| Declared dependency pairs (`artifacts.json`) | {con['declared_dependency_pairs']} |",
        f"| Declared but not projected (hidden dependencies) | "
        f"**{len(con['declared_not_projected'])}** |",
        f"| Projected but not declared (metadata-derived, by design) | "
        f"{con['projected_not_declared_count']} |",
        f"| Duplicate edge ids | **{len(con['duplicate_edge_ids'])}** |",
        f"| Endpoints not resolving to a registered artifact | "
        f"**{len(con['dependency_endpoints_unknown'])}** |",
        f"| Parent pairs | {con['parent_pairs']} |",
        "",
        "## 3. Nodes per identifier family",
        "",
        "| Family | Nodes |",
        "|---|---|",
    ]
    o7 += [f"| `{k}` | {v} |" for k, v in sorted(prog.items(), key=lambda i: (-i[1], i[0]))]
    o7 += [
        "",
        "## 4. The corrected ENG segment",
        "",
        "Dependency depth (level) of each Engineering-Foundation instrument. A strictly",
        "increasing level along the constitutional sequence is the proof that the graph",
        "now founds each primitive only after the primitive it presupposes",
        "(`ENG-GOV-001` Output 11 Option B; `ENG-000` ENG-L-05/06).",
        "",
        "| Level | Universal id | Native id | Instrument |",
        "|---|---|---|---|",
    ]
    o7 += [
        f"| {depth_of[uid]} | `{uid}` | `{native}` | {title} |" for uid, native, title in ENG_SPINE
    ]
    o7 += [
        "",
        "## 5. Gate verdict over this graph",
        "",
        "```json",
        json.dumps(dep["validation_report"], indent=2, sort_keys=True),
        "```",
        "",
        "---",
        "",
        f"**DEPENDENCY GRAPH ACYCLIC · SCC>1 = {dep['scc_gt1_count']} · "
        f"{dep['artifact_nodes']} NODES · {dep['depends_on_edges']} EDGES**",
        "",
    ]
    (OUT / "07-UPDATED-DEPENDENCY-GRAPH.md").write_text("\n".join(o7))

    # ---------------------------------------------------------------- Output 8
    o8 = [
        "# Output 8 — Updated Critical Path",
        "",
        HDR.format(owner="`engine/graph/architecture/critical_path.py` (UCOS-EPIC-010)"),
        "",
        "---",
        "",
        "## 1. Assessment",
        "",
        "| Metric | Baseline | Post-remediation |",
        "|---|---|---|",
        f"| Length (artifacts) | 164 | {dep['critical_path_length']} |",
        f"| Cyclic | true | **{str(dep['critical_path_cyclic']).lower()}** |",
        "| Well-defined | only via SCC condensation | **directly on the DAG** |",
        "",
        "The length is unchanged; its *meaning* is not. At baseline the longest path was",
        "computable only because the engine collapsed the ENG cycle into one weighted",
        "super-node. The path is now a genuine chain of single artifacts, so",
        '"dependency depth" is a real measurement rather than an artefact of condensation.',
        "",
        "Ties break on the smallest component root id, so the path is reproducible.",
        "",
        "## 2. Direction",
        "",
        "Each entry **depends on** the next. Read bottom-to-top for build/authoring order.",
        "",
        "## 3. The path",
        "",
        f"{dep['critical_path_length']} artifacts:",
        "",
        "| # | Universal id | Level |",
        "|---|---|---|",
    ]
    o8 += [f"| {i + 1} | `{n}` | {depth_of[n]} |" for i, n in enumerate(path)]
    o8 += [
        "",
        "## 4. The ENG segment of the path",
        "",
        "The corrected segment, in dependency direction:",
        "",
        "```",
        "UCOS-RUN-000001",
        "  → UCOS-ENG-000007  (ENG-005 Universal Relationship & Reference System)",
        "  → UCOS-ENG-000008  (ENG-004 Universal Type System)",
        "  → UCOS-ENG-000009  (ENG-003 Universal Value System)",
        "  → UCOS-ENG-000006  (ENG-002 Universal Object System)",
        "  → UCOS-ENG-000005  (ENG-001 Universal Identity System)",
        "  → UCOS-ENG-000003  (ENG-000 Engineering Program Master Index)",
        "  → UCOS-ARCH-000004",
        "```",
        "",
        "Reversed into authoring order this reads",
        "**ENG-000 → ENG-001 Identity → ENG-002 Object → ENG-003 Value → ENG-004 Type →",
        "ENG-005 Relationship & Reference** — `ENG-GOV-001` Output 11 Option B exactly.",
        "",
        "---",
        "",
        f"**CRITICAL PATH DERIVED · LENGTH {dep['critical_path_length']}"
        " · ACYCLIC · DETERMINISTIC**",
        "",
    ]
    (OUT / "08-UPDATED-CRITICAL-PATH.md").write_text("\n".join(o8))

    # ---------------------------------------------------------------- Output 9
    sizes = [len(g) for g in groups]
    singles = sizes.count(1)
    o9 = [
        "# Output 9 — Updated Parallel Execution Matrix",
        "",
        HDR.format(owner="`engine/graph` + `engine/graph/architecture/algorithms.py`"),
        "",
        "---",
        "",
        "## 1. Derivation",
        "",
        "Kahn levelisation of the `Depends-On` DAG with a sorted frontier. **Group *n*** is",
        "the set of artifacts whose every dependency lies in groups `0…n-1`. Members of a",
        "group therefore have no dependency on one another and may be executed",
        "concurrently; groups must be executed in ascending order. The sorted frontier makes",
        "the partition deterministic.",
        "",
        "This matrix is derivable **only because the graph is acyclic**. At baseline it",
        "terminated after 52 groups with 3 artifacts unorderable.",
        "",
        "## 2. Summary",
        "",
        "| Metric | Baseline | Post-remediation |",
        "|---|---|---|",
        "| Groups | 52 (truncated) | " + str(len(groups)) + " |",
        f"| Artifacts placed | 1196 of 1199 | **{sum(sizes)} of {dep['artifact_nodes']}** |",
        "| Unorderable artifacts | 3 | **0** |",
        f"| Widest group | — | {max(sizes)} (group 0) |",
        f"| Single-member groups | — | {singles} |",
        f"| Mean group width | — | {sum(sizes) / len(sizes):.2f} |",
        "",
        "Group 0 holds " + str(sizes[0]) + " artifacts with no dependency at all — the",
        "maximum immediately-parallel front. The long tail of single-member groups is the",
        "strictly sequential spine, and it is exactly the critical path.",
        "",
        "## 3. Matrix",
        "",
        "| Group | Width | Members |",
        "|---|---|---|",
    ]
    for i, g in enumerate(groups):
        if len(g) > 12:
            members = ", ".join(f"`{m}`" for m in g[:12]) + f", … (+{len(g) - 12} more)"
        else:
            members = ", ".join(f"`{m}`" for m in g)
        o9.append(f"| {i} | {len(g)} | {members} |")
    o9 += [
        "",
        "Full membership of every group, including group 0, is in",
        "`evidence/post/dependency-derivation.json` under `dependency.parallel_groups`.",
        "",
        "## 4. Engineering-Foundation placement",
        "",
        "| Group | Universal id | Native id | Instrument |",
        "|---|---|---|---|",
    ]
    o9 += [
        f"| {depth_of[uid]} | `{uid}` | `{native}` | {title} |" for uid, native, title in ENG_SPINE
    ]
    o9 += [
        "",
        "Six consecutive groups, strictly ascending: no two Engineering-Foundation",
        "primitives are scheduled concurrently, and none is scheduled before a primitive it",
        "presupposes.",
        "",
        "---",
        "",
        f"**PARALLEL EXECUTION MATRIX DERIVED · {len(groups)} GROUPS · "
        f"{sum(sizes)}/{dep['artifact_nodes']} PLACED · 0 UNORDERABLE**",
        "",
    ]
    (OUT / "09-UPDATED-PARALLEL-EXECUTION-MATRIX.md").write_text("\n".join(o9))

    print("wrote 07-UPDATED-DEPENDENCY-GRAPH.md")
    print("wrote 08-UPDATED-CRITICAL-PATH.md")
    print("wrote 09-UPDATED-PARALLEL-EXECUTION-MATRIX.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
