"""Read-only integration tests over the real 00-BOOK/DATA registry substrate.

These assert the Universal Knowledge Graph is *operational* against the certified
corpus (the mission success criterion) and that it reads it without mutation
(DP-03). Skipped automatically when the corpus is unavailable.
"""

from __future__ import annotations

from engine.graph.adapter import KnowledgeGraphAdapter
from engine.graph.evidence import build_evidence
from engine.graph.projections import PROJECTION_NAMES


def test_real_core_graph_builds(real_data_dir):
    kg = KnowledgeGraphAdapter.open(real_data_dir)
    core = kg.core
    # Node count == artifacts + volumes; edge count == relationships. Derived from
    # the live registry (the corpus is regenerated by the repo's own hooks, so
    # exact totals drift — the projection invariant is what matters).
    expected_nodes = kg.registry.artifacts.count() + kg.registry.volumes.count()
    assert core.order() == expected_nodes
    assert core.size() == kg.registry.graph.count()
    assert "Artifact" in core.kinds()
    assert "Depends-On" in core.edge_types()


def test_real_no_duplicate_nodes_and_immutable_ids(real_data_dir):
    kg = KnowledgeGraphAdapter.open(real_data_dir)
    report = kg.validate()
    assert report.duplicate_node_ids == ()
    assert report.malformed_node_ids == ()
    assert report.malformed_edge_ids == ()
    assert report.unversioned_artifacts == ()
    assert report.is_valid is True


def test_real_all_projections_operational(real_data_dir):
    kg = KnowledgeGraphAdapter.open(real_data_dir)
    for name in PROJECTION_NAMES:
        proj = kg.projection(name)
        assert proj.summary()["nodes"] >= 0
    # certification projection reflects the certified verdict
    assert kg.certification_graph().verdict() == "CERTIFIED"


def test_real_evidence_is_operational(real_data_dir):
    kg = KnowledgeGraphAdapter.open(real_data_dir)
    evidence = build_evidence(kg)
    assert evidence["operational"] is True
    expected_nodes = kg.registry.artifacts.count() + kg.registry.volumes.count()
    assert evidence["core"]["nodes"] == expected_nodes
    assert len(evidence["projections"]) == 10
    assert evidence["exemplars"]["blast_radius"] >= 1


def test_real_read_only_source(real_source):
    # The graph reads the frozen corpus in place without mutating it (DP-03).
    assert real_source.is_within_frozen_corpus() is True
