"""Publication generation — one generator, unlimited formats.

There is deliberately **no** per-genre generator class. A paper, a journal article,
a conference paper, a white paper, a technical article, a patent draft and a standards
proposal differ only in their *format descriptor* — which sections, in which order,
with which renderer. The generator reads the descriptor, applies each section's
declared selector to the research corpus, and emits a reference-only
:class:`~intelligence.publication.model.PublicationSpec`.

Consequences:
  * adding a format adds zero code (see :class:`~intelligence.publication.formats.FormatRegistry`)
  * every format is generated by the same, once-validated code path
  * a reference selected for an earlier section is never repeated in a later one,
    so a document cannot restate its own content

The named convenience functions at the bottom exist only to give the mission's named
deliverables an explicit, discoverable API; each is a one-line format selection.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any

from intelligence.kernel.knowledge import CanonicalKnowledgeResolver, make_ref
from intelligence.publication.formats import FormatDescriptor, FormatRegistry
from intelligence.publication.model import (
    ROLE_EVIDENCE,
    ROLE_PRIMARY,
    ROLE_SUPPORT,
    ContentRef,
    PublicationSpec,
    SectionSpec,
    ordered_refs,
)
from intelligence.research.model import ResearchCorpus, ResearchUnit, ref_target

#: The structural label used when a publication covers the whole research corpus.
ALL_AREAS_LABEL = "ALL RESEARCH AREAS"
ALL_AREAS_KEY = "all-areas"

#: Role assigned to references drawn from each corpus collection.
_ROLE_BY_SOURCE = {
    "claims": ROLE_PRIMARY,
    "standards": ROLE_PRIMARY,
    "findings": ROLE_EVIDENCE,
    "contributions": ROLE_EVIDENCE,
    "sources": ROLE_SUPPORT,
}

#: Selection priority by canonical authority. A section with a limit (an abstract, an
#: executive summary) should draw the most authoritative claims first — deterministically,
#: from the canonical authority field, never from an editorial judgement.
_AUTHORITY_RANK: dict[str, int] = {
    "constitutional": 0,
    "architectural": 1,
    "engineering": 2,
    "advisory": 3,
}

#: Selection priority by lifecycle: live authority before proposed or retired.
_LIFECYCLE_RANK: dict[str, int] = {
    "operational": 0,
    "implemented": 1,
    "ratified": 2,
    "approved": 3,
    "proposed": 4,
    "draft": 5,
    "deprecated": 6,
    "superseded": 7,
    "retired": 8,
}


def _claim_priority(record: Any) -> tuple[int, int, str]:
    return (
        _AUTHORITY_RANK.get(getattr(record, "authority", ""), 99),
        _LIFECYCLE_RANK.get(getattr(record, "lifecycle", ""), 99),
        str(getattr(record, "claim_ref", "") or getattr(record, "standard_ref", "")),
    )


@dataclass(frozen=True, slots=True)
class PublicationScope:
    """What a publication is about: an area of the research corpus, or all of it."""

    scope_key: str
    area_label: str
    unit_id: str
    claims: tuple[Any, ...]
    findings: tuple[Any, ...]
    contributions: tuple[Any, ...]
    standards: tuple[Any, ...]

    @classmethod
    def whole_corpus(cls, corpus: ResearchCorpus) -> PublicationScope:
        return cls(
            scope_key=ALL_AREAS_KEY,
            area_label=ALL_AREAS_LABEL,
            unit_id="",
            claims=corpus.claims,
            findings=corpus.findings,
            contributions=corpus.contributions,
            standards=corpus.standards,
        )

    @classmethod
    def for_unit(cls, corpus: ResearchCorpus, unit: ResearchUnit) -> PublicationScope:
        claim_ids = set(unit.claim_ids)
        finding_ids = set(unit.finding_ids)
        contribution_ids = set(unit.contribution_ids)
        standard_ids = set(unit.standard_ids)
        return cls(
            scope_key=unit.natural_key,
            area_label=unit.area_label,
            unit_id=unit.unit_id,
            claims=tuple(c for c in corpus.claims if c.claim_id in claim_ids),
            findings=tuple(f for f in corpus.findings if f.finding_id in finding_ids),
            contributions=tuple(
                c for c in corpus.contributions if c.contribution_id in contribution_ids
            ),
            standards=tuple(s for s in corpus.standards if s.standard_id in standard_ids),
        )

    def collection(self, source: str) -> tuple[Any, ...]:
        return {
            "claims": self.claims,
            "findings": self.findings,
            "contributions": self.contributions,
            "standards": self.standards,
            "sources": (),
        }.get(source, ())

    def record_ids(self) -> tuple[str, ...]:
        return tuple(
            dict.fromkeys(
                [c.claim_id for c in self.claims]
                + [f.finding_id for f in self.findings]
                + [c.contribution_id for c in self.contributions]
                + [s.standard_id for s in self.standards]
            )
        )


class PublicationGenerator:
    """Generates reference-only publication specifications for any registered format."""

    def __init__(
        self,
        corpus: ResearchCorpus,
        resolver: CanonicalKnowledgeResolver,
        formats: FormatRegistry | None = None,
    ) -> None:
        self.corpus = corpus
        self.resolver = resolver
        self.formats = formats or FormatRegistry()

    # -- selection -------------------------------------------------------------

    def _candidate_refs(self, rule: Mapping[str, Any], scope: PublicationScope) -> list[str]:
        """Apply a declared section selector to the scoped corpus. Returns refs only."""
        source = str(rule.get("source"))
        records = self._ordered(source, scope.collection(source))
        claim_classes = set(rule.get("claim_classes") or ())
        finding_classes = set(rule.get("finding_classes") or ())
        ref_field = rule.get("ref")
        derive_space = rule.get("derive_space")
        derive_field = rule.get("derive_field")
        refs: list[str] = []
        for record in records:
            if claim_classes and getattr(record, "claim_class", None) not in claim_classes:
                continue
            if finding_classes and getattr(record, "finding_class", None) not in finding_classes:
                continue
            if derive_space and derive_field:
                anchor = getattr(record, "subject_ref", "") or getattr(record, "claim_ref", "")
                target = ref_target(anchor)
                if target:
                    refs.append(make_ref(str(derive_space), target, str(derive_field)))
                continue
            value = getattr(record, str(ref_field), None)
            if value is None:
                continue
            if isinstance(value, tuple | list):
                refs.extend(str(v) for v in value if v)
            else:
                refs.append(str(value))
        return refs

    @staticmethod
    def _ordered(source: str, records: tuple[Any, ...]) -> tuple[Any, ...]:
        """Deterministic selection order: authority first for claims/standards."""
        if source in {"claims", "standards"}:
            return tuple(sorted(records, key=_claim_priority))
        if source == "findings":
            return tuple(sorted(records, key=lambda r: r.metric_key))
        if source == "contributions":
            return tuple(sorted(records, key=lambda r: r.area))
        return records

    def _resolvable(self, refs: Sequence[str], used: set[str]) -> list[str]:
        """Keep refs that resolve and have not already been placed in this document."""
        kept: list[str] = []
        for ref in dict.fromkeys(refs):
            if ref in used or ref in kept:
                continue
            if self.resolver.exists(ref):
                kept.append(ref)
        return kept

    # -- title -----------------------------------------------------------------

    def _title_ref(self, scope: PublicationScope) -> str:
        """The canonical subject whose title anchors the publication (deterministic)."""
        preferred = ("foundational-claim", "determination", "specification-claim")
        for claim_class in preferred:
            candidates = sorted(
                (c for c in scope.claims if c.claim_class == claim_class),
                key=_claim_priority,
            )
            for claim in candidates:
                if self.resolver.exists(claim.subject_ref):
                    return claim.subject_ref
        for claim in sorted(scope.claims, key=_claim_priority):
            if self.resolver.exists(claim.subject_ref):
                return claim.subject_ref
        return ""

    def _subject_refs(self, scope: PublicationScope) -> tuple[str, ...]:
        return tuple(
            sorted(
                {
                    c.subject_ref
                    for c in scope.claims
                    if self.resolver.exists(c.subject_ref)
                }
            )
        )

    # -- generation ------------------------------------------------------------

    def build(
        self, format_id: str, scope: PublicationScope | None = None
    ) -> PublicationSpec:
        """Build the specification for one publication in one registered format."""
        descriptor = self.formats.get(format_id)
        target_scope = scope or PublicationScope.whole_corpus(self.corpus)
        title_ref = self._title_ref(target_scope)
        used: set[str] = {title_ref} if title_ref else set()
        sections: list[SectionSpec] = []
        for ordinal, section_key in enumerate(descriptor.sections, start=1):
            section_type = self.formats.section(section_key)
            if section_type.structural:
                sections.append(
                    SectionSpec(section_key=section_key, ordinal=ordinal, structural=True)
                )
                continue
            candidates = self._candidate_refs(section_type.rule, target_scope)
            selected = self._resolvable(candidates, used)
            limit = section_type.rule.get("limit")
            if isinstance(limit, int) and limit > 0:
                selected = selected[:limit]
            used.update(selected)
            role = _ROLE_BY_SOURCE.get(str(section_type.rule.get("source")), ROLE_PRIMARY)
            declared_role = section_type.rule.get("role")
            if isinstance(declared_role, str) and declared_role:
                role = declared_role
            sections.append(
                SectionSpec(
                    section_key=section_key,
                    ordinal=ordinal,
                    refs=ordered_refs([ContentRef(ref=r, role=role) for r in selected]),
                )
            )
        citation_refs = tuple(sorted(used - {""}))
        return PublicationSpec.create(
            format_id=descriptor.format_id,
            area_label=target_scope.area_label,
            genre=descriptor.genre,
            unit_id=target_scope.unit_id,
            title_ref=title_ref,
            subject_refs=self._subject_refs(target_scope),
            sections=tuple(sections),
            citation_refs=citation_refs,
            research_record_ids=target_scope.record_ids(),
        )

    def build_all(
        self, scope: PublicationScope | None = None, format_ids: Sequence[str] | None = None
    ) -> tuple[PublicationSpec, ...]:
        """Build one publication per requested format (default: every registered format)."""
        ids = list(format_ids) if format_ids else self.formats.format_ids()
        return tuple(self.build(format_id, scope) for format_id in sorted(ids))

    def build_by_genre(
        self, genre: str, scope: PublicationScope | None = None
    ) -> tuple[PublicationSpec, ...]:
        return self.build_all(scope, [f.format_id for f in self.formats.by_genre(genre)])

    def scopes(self) -> tuple[PublicationScope, ...]:
        """Every publishable scope: the whole corpus plus each research area."""
        return (
            PublicationScope.whole_corpus(self.corpus),
            *(PublicationScope.for_unit(self.corpus, u) for u in self.corpus.units),
        )

    # -- named deliverables (explicit API over the same generic path) ----------

    def generate_paper(self, scope: PublicationScope | None = None) -> PublicationSpec:
        return self.build("research-paper", scope)

    def generate_journal_article(self, scope: PublicationScope | None = None) -> PublicationSpec:
        return self.build("journal-article", scope)

    def generate_conference_paper(self, scope: PublicationScope | None = None) -> PublicationSpec:
        return self.build("conference-paper", scope)

    def generate_white_paper(self, scope: PublicationScope | None = None) -> PublicationSpec:
        return self.build("white-paper", scope)

    def generate_technical_article(self, scope: PublicationScope | None = None) -> PublicationSpec:
        return self.build("technical-article", scope)

    def generate_patent_draft(self, scope: PublicationScope | None = None) -> PublicationSpec:
        return self.build("patent-draft", scope)

    def generate_standards_proposal(self, scope: PublicationScope | None = None) -> PublicationSpec:
        return self.build("standards-proposal", scope)


#: The mission's named deliverables mapped to their default format id. Present so a
#: caller can enumerate them; every entry resolves through the same generic generator.
NAMED_DELIVERABLES: dict[str, str] = {
    "paper": "research-paper",
    "journal": "journal-article",
    "conference-paper": "conference-paper",
    "white-paper": "white-paper",
    "technical-article": "technical-article",
    "patent-draft": "patent-draft",
    "standards-proposal": "standards-proposal",
}


def descriptor_for_deliverable(name: str, formats: FormatRegistry) -> FormatDescriptor:
    return formats.get(NAMED_DELIVERABLES.get(name, name))


__all__ = [
    "ALL_AREAS_KEY",
    "ALL_AREAS_LABEL",
    "NAMED_DELIVERABLES",
    "PublicationGenerator",
    "PublicationScope",
    "descriptor_for_deliverable",
]
