"""URI-000001 — the generator strategy contract.

Every generator is a *strategy* over the same :class:`GenerationContext`. It receives
one composition unit, the canonical objects bound to it, and the artifacts every
upstream family already produced — and returns in-memory artifacts. A generator may
not:

* read the filesystem, the network, the environment, or a clock;
* seal, hash, or write its own output (the Generation Engine owns sealing and the
  Implementation Engine owns writing);
* introduce a fact that is not derivable from the canonical objects it was given.

That last constraint is what makes "everything generated from canonical knowledge"
mechanically true rather than aspirational: the context exposes canonical knowledge and
nothing else.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any

from engine.knowledge.cko import CanonicalKnowledgeObject, DecisionRecord
from intelligence.realization.canonical import document_json
from intelligence.realization.config import CAPABILITY_ID
from intelligence.realization.contracts import (
    ArtifactFamily,
    CompositionUnit,
    Envelope,
    GeneratedArtifact,
    Invariant,
    MediaKind,
    Provenance,
    RealizationComposition,
    RealizationPlan,
    RealizationTarget,
)
from intelligence.realization.errors import GenerationError
from intelligence.realization.knowledge import KnowledgeIntake

#: Emitted at the head of every generated text artifact so a reader can never mistake a
#: generated file for an authored one.
GENERATED_BANNER = (
    "GENERATED BY URI-000001 (Universal Realization Intelligence) — DO NOT EDIT.\n"
    "This file is derived from canonical knowledge (UKDA canonical store) and is\n"
    "regenerated deterministically. Edit the canonical knowledge, not this file."
)


@dataclass(frozen=True, slots=True)
class GenerationContext:
    """Everything a generator is allowed to see, and nothing else."""

    intake: KnowledgeIntake
    plan: RealizationPlan
    composition: RealizationComposition
    unit: CompositionUnit
    target: RealizationTarget
    upstream: Mapping[str, tuple[GeneratedArtifact, ...]] = field(default_factory=dict)

    # -- canonical knowledge access -------------------------------------------

    @property
    def objects(self) -> tuple[CanonicalKnowledgeObject, ...]:
        """The canonical objects bound to this unit, ordered by id."""
        return tuple(
            self.intake.base.require_object(cko_id) for cko_id in self.unit.bound_ckos
        )

    @property
    def decisions(self) -> tuple[DecisionRecord, ...]:
        """The canonical decisions this unit's knowledge cites."""
        return tuple(
            self.intake.base.require_decision(did) for did in self.unit.bound_decisions
        )

    @property
    def invariants(self) -> tuple[Invariant, ...]:
        return self.target.invariants

    @property
    def universe(self) -> str:
        return self.target.universe

    def objects_of_kind(self, kind: str) -> tuple[CanonicalKnowledgeObject, ...]:
        return tuple(obj for obj in self.objects if obj.kind.value == kind)

    def upstream_paths(self, family: ArtifactFamily) -> tuple[str, ...]:
        """Paths already produced for ``family`` in this target — for cross-references."""
        return tuple(
            sorted(art.relative_path for art in self.upstream.get(family.value, ()))
        )

    def upstream_artifact(self, family: ArtifactFamily, suffix: str) -> str | None:
        """The single upstream artifact path in ``family`` ending with ``suffix``."""
        for path in self.upstream_paths(family):
            if path.endswith(suffix):
                return path
        return None

    # -- artifact construction (the only way to produce output) ----------------

    def provenance(self, generator: str, generator_version: str) -> Provenance:
        return Provenance(
            generator=generator,
            generator_version=generator_version,
            capability=CAPABILITY_ID,
            plan_id=self.composition.plan_id,
            step_id=self.unit.step_id,
            unit_id=self.unit.unit_id,
            target_id=self.unit.target_id,
            knowledge_seal=self.intake.knowledge_seal,
            source_ckos=self.unit.bound_ckos,
            source_decisions=self.unit.bound_decisions,
        )

    def envelope(
        self,
        *,
        artifact_id: str,
        title: str,
        document_format: str,
        extra: Mapping[str, Any] | None = None,
    ) -> dict[str, Any]:
        return Envelope(
            artifact_id=artifact_id,
            title=title,
            document_format=document_format,
            knowledge_seal=self.intake.knowledge_seal,
            extra=dict(extra or {}),
        ).to_dict()


class Generator:
    """Base class for the seven realization generators."""

    #: The artifact family this generator realizes. Subclasses must set it.
    family: ArtifactFamily
    #: Stable generator identity recorded in every artifact's provenance.
    name: str = "uri.generator"
    version: str = "1.0.0"

    def generate(self, context: GenerationContext) -> tuple[GeneratedArtifact, ...]:
        """Return the artifacts this generator derives from ``context``."""
        raise NotImplementedError

    # -- helpers available to every subclass ----------------------------------

    def artifact(
        self,
        context: GenerationContext,
        *,
        relative_path: str,
        media: MediaKind,
        content: str,
    ) -> GeneratedArtifact:
        if not content.endswith("\n"):
            raise GenerationError(
                "generated content must be newline-terminated",
                generator=self.name,
                path=relative_path,
            )
        return GeneratedArtifact(
            relative_path=relative_path,
            family=self.family,
            media=media,
            content=content,
            provenance=context.provenance(self.name, self.version),
        )

    def json_artifact(
        self,
        context: GenerationContext,
        *,
        relative_path: str,
        payload: Mapping[str, Any],
    ) -> GeneratedArtifact:
        body = dict(payload)
        body["provenance"] = context.provenance(self.name, self.version).to_dict()
        return self.artifact(
            context,
            relative_path=relative_path,
            media=MediaKind.JSON,
            content=document_json(body),
        )

    def text_artifact(
        self,
        context: GenerationContext,
        *,
        relative_path: str,
        media: MediaKind,
        lines: Sequence[str],
    ) -> GeneratedArtifact:
        return self.artifact(
            context,
            relative_path=relative_path,
            media=media,
            content="\n".join(lines).rstrip("\n") + "\n",
        )

    def provenance_comment(self, context: GenerationContext, prefix: str) -> list[str]:
        """Render the generated banner + provenance as comment lines for ``prefix``."""
        prov = context.provenance(self.name, self.version)
        lines = [f"{prefix} {line}" for line in GENERATED_BANNER.splitlines()]
        lines.append(f"{prefix}")
        for key, value in sorted(prov.to_dict().items()):
            rendered = ", ".join(value) if isinstance(value, list) else value
            lines.append(f"{prefix} {key}: {rendered}")
        return lines


__all__ = ["GENERATED_BANNER", "GenerationContext", "Generator"]
