#!/usr/bin/env bash
#
# UCOS Ω∞ — Generated-prerequisite regeneration (P0-BLOCKER-ERADICATION-001).
#
#   ./scripts/generate-prerequisites.sh
#   PYTHON=/path/to/python ./scripts/generate-prerequisites.sh
#
# THE one definition of "re-derive the generated inputs the gates read". Four trees are
# excluded from version control on the STATED grounds that they are "regenerated each run":
#
#   knowledge/                          ucos-knowledge init      (engine.knowledge.cli)
#   determinism-evidence/               ec1-determinism          (engine.determinism.reproduce)
#   00-MASTER/UAKOS-CLOSURE-002/*.md    make closure             (closure_engine.py)
#   …/closure.json · phase2 · phase3    make closure-phase2/3    (phase2/phase3_engine.py)
#
# Nothing ran them. The exclusion asserted a regeneration no entry point performed, so every
# consumer read them only by accident of local residue. Measured consequences on a clean
# checkout of 404568e: 51 of 10201 tests failed, and five constitutional gate engines
# reported a declared reference as unresolvable —
#   UCL-000001   REC-KNOWLEDGE: record owner does not resolve: knowledge/canonical-knowledge.json
#   ACEE-000001  a cited owner does not resolve: CAP-08 → knowledge/canonical-knowledge.json
#   UCCEP-000000 PROGRAM-000008: reference does not resolve: 00-MASTER/UAKOS-CLOSURE-002/…
#   UCOS-AEE-001 OBS-READINESS-WRITE-SCOPE: reference does not resolve: 00-MASTER/UAKOS-…
#   UCOS-RIB-001 matrices.MTX-PRIORITY: canonical owner does not resolve: …/42-…
# — every one of which PASSES once these four producers have run. The declarations were
# correct; the inputs were simply never re-derived.
#
# Deliberately STDLIB-ONLY and venv-free. The constitutional gate workflows are stdlib-only
# by design (no bootstrap, no pinned toolchain, `python3` straight from setup-python), so a
# prerequisite step that needed the venv could not run there — and those are exactly the jobs
# that were failing. Verified: all four producers exit 0 under a bare `python3`.
#
# Writes ONLY to the four ignored trees above, so running this can never dirty the working
# tree and can never be seen as drift by the Registration Gate.
#
# `init --force` is deliberate and required for IDEMPOTENCE. Plain `init` refuses an existing
# store ("canonical store already exists … use --force") and exits 1, so a bare `init` works
# exactly once per checkout and fails on every subsequent run — a verification stage that can
# only run on a virgin tree is not a verification stage. The store is deterministically
# re-derived from engine/knowledge/seed.py, the single authored source, and is ignored by
# version control, so overwriting it discards nothing: re-deriving output from its own source
# is the whole reason it is declared re-derivable.

set -euo pipefail
cd "$(dirname "$0")/.."

PY="${PYTHON:-python3}"

# The knowledge store is a THREE-step pipeline, not one. RTBD-001 §3.2 declares it as
# `init` (11 seeded constitutional CKOs) -> `capabilities --write` (+110 capability facts
# projected from the tracked capability catalogue) -> `docs` (10 handbooks), and verifies
# the result byte-identically at 121 CKOs. Running `init` alone leaves the store at 11 and
# the handbooks unwritten, so every consumer measured a store truncated to 9% of itself:
# ACEE-000001 reported PRV-KNOWLEDGE objects=11 against a committed register of 121, and
# `knowledge/handbooks/` — regenerable output the ignore authority excludes on the stated
# grounds that it is "regenerated each run" — was regenerated by nothing.
#
# That made register content depend on WHICH generation steps had been run rather than on
# repository state alone, which is drift by definition. All three steps are idempotent and
# write only inside the ignored `knowledge/` tree.
"$PY" -m engine.knowledge.cli init --force            >/dev/null
"$PY" -m engine.knowledge.cli capabilities --write    >/dev/null
"$PY" -m engine.knowledge.cli docs                    >/dev/null
"$PY" -m engine.determinism.reproduce                 >/dev/null
"$PY" 00-MASTER/UAKOS-CLOSURE-002/closure_engine.py   >/dev/null
"$PY" 00-MASTER/UAKOS-CLOSURE-002/phase2_engine.py    >/dev/null
"$PY" 00-MASTER/UAKOS-CLOSURE-002/phase3_engine.py    >/dev/null

# UCOS-RC-004 — the research corpus and publication set belong to this list for exactly the
# reason everything above does: both are excluded from version control on the stated ground
# that they are regenerated each run, and both are READ as evidence by a tracked consumer.
#
# UCDA-000001 resolves decision DEC-CAEM-04's coverage against `intelligence/UCOS-URI-001`
# (EQ-4) and `intelligence/UCOS-UPI-001` (EQ-5). Measured on a pristine clone at 3af66dcc:
# both resolved to [] because nothing had produced them, dropping that decision from
# complete to incomplete and `dimensions_covered` from 278 to 276 — after the knowledge
# store fix had already recovered the other four. The declaration was right; the producer
# simply never ran outside a working tree that happened to retain earlier output.
#
# This is the same defect the header above describes, one directory further out: an
# exclusion asserting a regeneration that no entry point performed.
"$PY" -m intelligence.research    build >/dev/null
"$PY" -m intelligence.publication build >/dev/null

# UCOS-GOV-FOUNDATION — the provenance baseline belongs here for the same reason, and its
# absence is a harder failure than a drop in coverage: UAKOS-PHASE-001A-R1 READS
# `00-MASTER/UAKOS-PHASE-001B/provenance.json` at module import and cannot render without it.
# The file is excluded from version control by the same 00-MASTER GPR-001 rule as every other
# engine JSON state, so a pristine clone had no way to obtain it — all twelve of that
# programme's tracked registers, including 00-FINAL-CONSTITUTIONAL-BASELINE-CERTIFICATION.md,
# stood on a generated input that nothing in the declared bootstrap produced.
#
# GENERATED_INPUT_HAS_PRODUCER_AND_BOOTSTRAP now refuses that declaration, and this line is
# what discharges it. It runs AFTER the closure phases because the provenance engine reads
# `00-MASTER/UAKOS-CLOSURE-002/closure.json`, which phase 1 above produces.
"$PY" 00-MASTER/UAKOS-PHASE-001B/provenance_engine.py >/dev/null

# UCOS-UGA-001 — `realization/` was the LAST open bootstrap gap: the generated-artifact
# registry declared a producer and a bootstrap_command for it, and recorded the stage as
# "NOT IN THE BOOTSTRAP — see bootstrap_gaps". A pristine clone running ./verify.sh did not
# create it, so UGA-INV-06 (EVERY_GENERATED_INPUT_HAS_BOOTSTRAP_PATH) failed against it.
#
# It could not simply be added here, because the producer was not deterministic. The
# manifest sealed the per-file `action` — "created" on a clone that lacked the files,
# "unchanged" on every later pass — so identical canonical knowledge produced two different
# implementation identities and realization/UCOS-URI-MANIFEST.json had no fixed point. Wiring
# a non-deterministic producer into the bootstrap would have injected that variance into
# every verification run and broken the Phase-8 fixed point outright.
#
# The capability was completed rather than the declaration relaxed: `action` is an execution
# observation, so it is excluded from the seal and from the manifest (UAKOS-CLOSURE-008 — an
# execution transcript is evidence, never identity) and retained on the returned record, in
# the structured log and in the evidence documents. Measured after the fix: a wiped tree and
# a steady-state tree now produce the SAME digest in ONE pass.
#
# Writes only inside the ignored `realization/` tree, so it cannot dirty the working tree.
"$PY" -m intelligence.realization realize >/dev/null

echo "generated prerequisites: knowledge · determinism-evidence · closure phases 1-3 · research · publication · provenance · realization" >&2

# UCOS-UCTX-001 — the generated context projections (Model B).
#
# Decision-01 made every context projection a PRODUCT rather than tracked truth, so a fresh
# clone arrives with no CLAUDE.md, no AGENTS.md, no .cursor rule and no context root at all.
# That is the correct storage posture and a dangerous default: the condition this whole
# capability exists to prevent is an agent operating with no governed context.
#
# This line is what keeps the two facts from becoming the same thing. The projections are
# declared in generated_inputs with this exact bootstrap_command, so UGA-INV-06 refuses the
# declaration if this stage stops producing them — the bootstrap obligation is measured, not
# remembered. It runs before the context gate stage, so a clone is in a governed state by the
# time anything reads it.
#
# Deterministic and idempotent: identical inputs produce identical bytes and a second run
# writes nothing, so wiring it here injects no variance into the Phase-8 fixed point.
# Writes only the paths the exclusion register classifies GENERATED_DETERMINISTIC, so it
# cannot dirty the tracked working tree.
"$PY" 00-BOOK/tools/ukctx.py build >/dev/null

echo "generated prerequisites: context projections (UCOS-UCTX-001)" >&2
