"""Ω-5 — exactly one disposition per artifact, and no orphan, unknown or authority-free state."""

from __future__ import annotations

import pytest

from engine.universal_discovery import classification
from engine.universal_discovery.model import (
    ARCHIVED,
    DISPOSITIONS,
    EXEMPTED,
    GENERATED,
    MEASURED,
    TRANSIENT,
    OmegaError,
)


def _classify(path: str, head: str = "", **overrides: object) -> tuple[str, str, str]:
    arguments: dict[str, object] = {
        "source_head": head,
        "measurable_packages": ("alpha.core", "beta"),
        "test_roots": ("alpha/tests",),
        "frozen": ("99-FREEZE/",),
        "declared_exemptions": {},
        "declared_transient": {},
    }
    arguments.update(overrides)
    return classification.classify(path, **arguments)  # type: ignore[arg-type]


# --------------------------------------------------------------------------- the five dispositions


def test_a_declared_transient_is_transient() -> None:
    disposition, rule, reason = _classify(
        "alpha/scratch.py", declared_transient={"alpha/scratch.py": "written per run"}
    )
    assert (disposition, rule) == (TRANSIENT, classification.RULE_TRANSIENT)
    assert "written per run" in reason


def test_a_frozen_tree_is_archived() -> None:
    disposition, rule, _reason = _classify("99-FREEZE/old/module.py")
    assert (disposition, rule) == (ARCHIVED, classification.RULE_ARCHIVED)


def test_the_frozen_prefix_itself_is_archived() -> None:
    disposition, _rule, _reason = _classify("99-FREEZE")
    assert disposition == ARCHIVED


@pytest.mark.parametrize(
    "marker",
    [
        "# DO NOT EDIT",
        "# auto-generated by a tool",
        "# Auto-Generated",
        "# generated by producer.py",
        "# @generated",
        "# machine-generated",
    ],
)
def test_a_producer_marker_in_the_head_is_generated(marker: str) -> None:
    """Content-keyed, so a generated file is generated wherever it is written."""
    disposition, rule, _reason = _classify("alpha/core/built.py", f"{marker}\nX = 1\n")
    assert (disposition, rule) == (GENERATED, classification.RULE_GENERATED)


def test_a_marker_below_the_window_is_not_a_declaration() -> None:
    """The window is bounded so a passing mention deep in a file cannot retire an obligation."""
    body = "\n" * (classification.MARKER_WINDOW + 5) + "# do not edit\n"
    disposition, _rule, _reason = _classify("alpha/core/x.py", body)
    assert disposition == MEASURED


def test_a_suite_module_is_measured_because_the_suite_runs_it() -> None:
    """Coverage omits tests from its denominator; the suite executing them still measures them."""
    disposition, rule, reason = _classify("alpha/tests/test_service.py")
    assert (disposition, rule) == (MEASURED, classification.RULE_MEASURED)
    assert "suite" in reason


def test_a_package_in_the_denominator_is_measured() -> None:
    disposition, rule, _reason = _classify("alpha/core/service.py")
    assert (disposition, rule) == (MEASURED, classification.RULE_MEASURED)


def test_a_declared_exemption_is_exempted_with_its_reason() -> None:
    disposition, rule, reason = _classify(
        "alpha/dead/module.py", declared_exemptions={"alpha.dead": "retired, zero tests"}
    )
    assert (disposition, rule) == (EXEMPTED, classification.RULE_DECLARED_EXEMPT)
    assert "retired, zero tests" in reason


def test_a_root_python_could_not_name_is_exempted_by_the_language_rule() -> None:
    """The honest disposition of the governance engines: owned, invoked, unnameable as a source."""
    disposition, rule, reason = _classify("00-MASTER/UCI-000001/uci_engine.py")
    assert (disposition, rule) == (EXEMPTED, classification.RULE_UNNAMEABLE)
    assert "not a Python identifier" in reason


def test_a_path_no_import_could_name_is_exempted() -> None:
    disposition, rule, _reason = _classify("alpha/has-a-dash/module.py")
    assert (disposition, rule) == (EXEMPTED, classification.RULE_UNNAMEABLE)


def test_the_last_rule_is_unconditional_and_is_the_uncomfortable_one() -> None:
    """Ω-C-07: everything the earlier rules could not explain, in one named, ratcheted bucket."""
    disposition, rule, reason = _classify("gamma/unmeasured.py")
    assert (disposition, rule) == (EXEMPTED, classification.RULE_UNEXPLAINED)
    assert "FINDING" in reason


# ---------------------------------------------------------------------------- order and totality


def test_transient_beats_every_other_rule() -> None:
    disposition, _rule, _reason = _classify(
        "99-FREEZE/x.py",
        "# do not edit\n",
        declared_transient={"99-FREEZE/x.py": "declared"},
    )
    assert disposition == TRANSIENT


def test_archived_beats_generated() -> None:
    disposition, _rule, _reason = _classify("99-FREEZE/x.py", "# auto-generated\n")
    assert disposition == ARCHIVED


def test_generated_beats_measured() -> None:
    """A producer owns the bytes, so measuring them would measure the producer twice."""
    disposition, _rule, _reason = _classify("alpha/core/x.py", "# @generated\n")
    assert disposition == GENERATED


def test_every_classification_records_a_rule_and_a_checkable_reason() -> None:
    for path in (
        "alpha/core/x.py",
        "alpha/tests/test_x.py",
        "99-FREEZE/x.py",
        "00-MASTER/P/e.py",
        "gamma/x.py",
    ):
        disposition, rule, reason = _classify(path)
        assert disposition in DISPOSITIONS
        assert rule and reason, f"{path} classified with no rule or no reason"


def test_totality_is_asserted_and_names_the_offenders() -> None:
    with pytest.raises(OmegaError, match="not total"):
        classification.assert_total({"a.py": ("NOT-A-DISPOSITION", "R", "why")})
    with pytest.raises(OmegaError, match="not total"):
        classification.assert_total({"a.py": (MEASURED, "", "why")})
    with pytest.raises(OmegaError, match="not total"):
        classification.assert_total({"a.py": (MEASURED, "R", "")})
    classification.assert_total({"a.py": (MEASURED, "Ω-C-04", "because")})


def test_the_exemption_rules_are_named_as_a_population() -> None:
    """Each exemption rule's size is ratcheted, so the set must be enumerable in one place."""
    assert set(classification.EXEMPTION_RULES) == {
        classification.RULE_DECLARED_EXEMPT,
        classification.RULE_UNNAMEABLE,
        classification.RULE_UNEXPLAINED,
    }


# ------------------------------------------------------------------ the real repository, measured


def test_the_real_repository_has_no_unknown_or_orphan_state() -> None:
    from engine.universal_discovery import surface

    omega = surface.build(".")
    assert len(omega.artifacts) == len(omega.population.paths)
    for artifact in omega.artifacts:
        assert artifact.disposition in DISPOSITIONS
        assert artifact.disposition_rule and artifact.disposition_reason
    counted = sum(
        entry["files"]
        for entry in omega.totals["by_disposition"].values()  # type: ignore[union-attr]
    )
    assert counted == len(
        omega.artifacts
    ), "the dispositions do not partition the population, so an artifact holds two or none"


def test_the_unexplained_bucket_is_small_and_every_member_is_nameable() -> None:
    """Ω-C-07 is the honesty of the design, so its contents are reported rather than tolerated."""
    from engine.universal_discovery import surface

    omega = surface.build(".")
    unexplained = omega.by_rule(classification.RULE_UNEXPLAINED)
    # Not a ceiling — the CONVERGENT ratchet owns the bound. This asserts only that the bucket is
    # a finite, inspectable finding rather than a silent remainder.
    assert len(unexplained) < len(omega.artifacts) // 10
    for artifact in unexplained:
        assert artifact.authority, f"{artifact.path} is unexplained AND unowned"
