"""EPIC-VAL-003 — Repository Governance Report (Terminal T3).

The **Repository Governance Report** is the single canonical artifact the pipeline
emits — the deliverable of the end-to-end constitutional governance flow. It bundles
every unified artifact the mission requires, each generated by reusing the existing
engines (no re-implementation):

    * ``units`` — the per-unit Validation Report + Certification Decision (with their
      evidence and ledger entries) — the traceable governance trail.
    * ``repository_decision`` — the **unified repository decision** (fail-closed
      GOVERNED / NOT-GOVERNED across validation, certification, and acceptance).
    * ``repository_acceptance`` — the **unified repository acceptance** (the
      Acceptance Decision).
    * ``repository_certificate`` — the **unified repository certificate** (the
      immutable, content-addressed Acceptance Record).
    * ``repository_readiness`` — the **unified repository readiness** (the
      freeze-readiness report).
    * ``governance_evidence`` — the **unified governance evidence** (the closed
      Validation → Certification → Acceptance → Ledger evidence chain).
    * ``freeze_recommendation`` — the architecture **freeze recommendation**.

The report is self-verifying: its ``governance_sha256`` is a canonical hash binding
every subordinate artifact's own content hash, so the whole determination is
tamper-evident and reproducible (IMP-007 §5) — an identical input yields a
byte-identical report. It asserts ``ENGINEERING-EXECUTION-ONLY`` authority: it
records engineering readiness, never constitutional finality (DE-05 / IP-01).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from engine.governance.contracts import (
    GOVERNANCE_AUTHORITY,
    GovernanceStatus,
    RepositoryDecision,
    content_hash,
)
from engine.governance.errors import GovernanceIntegrityError

if TYPE_CHECKING:  # pragma: no cover - typing only
    from engine.acceptance.engine import AcceptanceDecision
    from engine.acceptance.readiness import RepositoryReadiness
    from engine.certification.engine import CertificationDecision
    from engine.certification.evidence import CertificationEvidence
    from engine.certification.ledger import CertificationLedger, CertificationLedgerEntry
    from engine.governance.evidence import GovernanceEvidence
    from engine.governance.freeze import FreezeRecommendation
    from engine.validation.contracts import ValidationReport
    from engine.validation.evidence import ValidationEvidence

#: The repository governance report format identifier.
REPORT_FORMAT = "ucos-repository-governance-report/1.0.0"


@dataclass(frozen=True, slots=True)
class GovernedUnit:
    """The full governance trail of one implementation unit (validation → ledger).

    Immutable and deterministic: it binds a unit's Validation Report and its
    Validation Evidence to the Certification Decision, Certification Evidence, and
    append-only ledger entry that aggregate it — the per-unit traceability record
    the unified evidence closes over.
    """

    unit_id: str
    validation_report: ValidationReport
    validation_evidence: ValidationEvidence
    certification_decision: CertificationDecision
    certification_evidence: CertificationEvidence
    ledger_entry: CertificationLedgerEntry

    @property
    def validated(self) -> bool:
        return self.validation_report.accepted

    @property
    def certified(self) -> bool:
        return self.certification_decision.certified

    def to_dict(self) -> dict[str, Any]:
        return {
            "unit_id": self.unit_id,
            "validated": self.validated,
            "certified": self.certified,
            "validation_report": self.validation_report.to_dict(),
            "validation_evidence": self.validation_evidence.to_dict(),
            "certification_decision": self.certification_decision.to_dict(),
            "certification_evidence": self.certification_evidence.to_dict(),
            "ledger_entry": self.ledger_entry.to_dict(),
        }


@dataclass(frozen=True, slots=True)
class RepositoryGovernanceReport:
    """The single canonical artifact of the end-to-end governance pipeline."""

    repository_id: str
    epic_id: str
    status: GovernanceStatus
    units: tuple[GovernedUnit, ...]
    ledger: CertificationLedger
    repository_decision: RepositoryDecision
    repository_acceptance: AcceptanceDecision
    repository_certificate: AcceptanceRecordType
    repository_readiness: RepositoryReadiness
    governance_evidence: GovernanceEvidence
    freeze_recommendation: FreezeRecommendation
    authority: str
    governance_sha256: str

    @staticmethod
    def _core(
        *,
        repository_id: str,
        epic_id: str,
        status: GovernanceStatus,
        unit_ids: tuple[str, ...],
        decision_sha256: str,
        acceptance_id: str,
        certificate_sha256: str,
        readiness_sha256: str,
        evidence_sha256: str,
        freeze_sha256: str,
        ledger_head: str,
        authority: str,
    ) -> dict[str, Any]:
        """The canonical, hashable core binding every subordinate artifact hash."""
        return {
            "repository_id": repository_id,
            "epic_id": epic_id,
            "status": status.value,
            "unit_ids": list(unit_ids),
            "decision_sha256": decision_sha256,
            "acceptance_id": acceptance_id,
            "certificate_sha256": certificate_sha256,
            "readiness_sha256": readiness_sha256,
            "evidence_sha256": evidence_sha256,
            "freeze_sha256": freeze_sha256,
            "ledger_head": ledger_head,
            "authority": authority,
        }

    @classmethod
    def assemble(
        cls,
        *,
        units: tuple[GovernedUnit, ...],
        ledger: CertificationLedger,
        decision: RepositoryDecision,
        acceptance: AcceptanceDecision,
        readiness: RepositoryReadiness,
        governance_evidence: GovernanceEvidence,
        freeze_recommendation: FreezeRecommendation,
        authority: str = GOVERNANCE_AUTHORITY,
    ) -> RepositoryGovernanceReport:
        """Assemble the content-addressed report from every unified artifact."""
        core = cls._core(
            repository_id=decision.repository_id,
            epic_id=decision.epic_id,
            status=decision.status,
            unit_ids=tuple(u.unit_id for u in units),
            decision_sha256=decision.decision_sha256,
            acceptance_id=acceptance.acceptance_id,
            certificate_sha256=acceptance.record.content_sha256,
            readiness_sha256=readiness.readiness_sha256,
            evidence_sha256=governance_evidence.evidence_sha256,
            freeze_sha256=freeze_recommendation.recommendation_sha256,
            ledger_head=ledger.head_hash,
            authority=authority,
        )
        return cls(
            repository_id=decision.repository_id,
            epic_id=decision.epic_id,
            status=decision.status,
            units=units,
            ledger=ledger,
            repository_decision=decision,
            repository_acceptance=acceptance,
            repository_certificate=acceptance.record,
            repository_readiness=readiness,
            governance_evidence=governance_evidence,
            freeze_recommendation=freeze_recommendation,
            authority=authority,
            governance_sha256=content_hash(core),
        )

    @property
    def governed(self) -> bool:
        return self.status is GovernanceStatus.GOVERNED

    def recompute_hash(self) -> str:
        """Recompute the governance root hash from the current subordinate hashes."""
        return content_hash(
            self._core(
                repository_id=self.repository_id,
                epic_id=self.epic_id,
                status=self.status,
                unit_ids=tuple(u.unit_id for u in self.units),
                decision_sha256=self.repository_decision.decision_sha256,
                acceptance_id=self.repository_acceptance.acceptance_id,
                certificate_sha256=self.repository_certificate.content_sha256,
                readiness_sha256=self.repository_readiness.readiness_sha256,
                evidence_sha256=self.governance_evidence.evidence_sha256,
                freeze_sha256=self.freeze_recommendation.recommendation_sha256,
                ledger_head=self.ledger.head_hash,
                authority=self.authority,
            )
        )

    def verify_integrity(self) -> bool:
        """Return True iff the stored root hash matches a recomputation."""
        return self.recompute_hash() == self.governance_sha256

    def require_integrity(self) -> None:
        """Raise :class:`GovernanceIntegrityError` if the report was mutated."""
        if not self.verify_integrity():
            raise GovernanceIntegrityError(
                "governance report integrity check failed (content mutated)",
                repository_id=self.repository_id,
                expected=self.governance_sha256,
                actual=self.recompute_hash(),
            )

    def to_dict(self) -> dict[str, Any]:
        return {
            "report_format": REPORT_FORMAT,
            "repository_id": self.repository_id,
            "epic_id": self.epic_id,
            "status": self.status.value,
            "governed": self.governed,
            "authority": self.authority,
            "units": [u.to_dict() for u in self.units],
            "ledger": self.ledger.to_dict(),
            "repository_decision": self.repository_decision.to_dict(),
            "repository_acceptance": self.repository_acceptance.to_dict(),
            "repository_certificate": self.repository_certificate.to_dict(),
            "repository_readiness": self.repository_readiness.to_dict(),
            "governance_evidence": self.governance_evidence.to_dict(),
            "freeze_recommendation": self.freeze_recommendation.to_dict(),
            "governance_sha256": self.governance_sha256,
        }


# A local alias so the annotation reads clearly without importing at runtime.
if TYPE_CHECKING:  # pragma: no cover - typing only
    from engine.acceptance.contracts import AcceptanceRecord as AcceptanceRecordType
else:  # pragma: no cover - runtime placeholder for the forward annotation
    AcceptanceRecordType = Any


__all__ = [
    "REPORT_FORMAT",
    "GovernedUnit",
    "RepositoryGovernanceReport",
]
