#!/usr/bin/env python3
"""
UCOS Ω∞ — Universal Context Generator (UCOS-UCTX-001).

The producer of the CANONICAL CONTEXT ROOT (00-BOOK/CONTEXT) and of every
agent-facing context surface the repository emits.

WHAT THIS IS NOT. It is not an authority and it holds none. It reads
00-BOOK/DATA/context-authority.json — itself a PROJECTION bound under
UCKP-LAW-0001 by UCOS-CAA-001 — plus the instruments that declaration NAMES,
and it writes views of what those instruments already say. Under UCKP-ART-11 a
generated view never owns truth; under UCKP-ART-03 authoring the same knowledge
a second time is void. Every sentence this generator emits therefore has a
source in a tracked instrument, and the manifest records which one.

WHY AN AGENT SURFACE MUST BE GENERATED. Measured at fce3cb9b, no agent surface
in this repository claimed authority — and none received any context either.
That is not a safe steady state: it is the state in which the first hand-written
CLAUDE.md silently becomes repository truth, on one branch, under no authority,
listed in no register. Making the surface generated converts that from an
editorial risk into a drift failure (INV-CTX-07).

DETERMINISM (UCKP-ART-13). Reads only the declaration and the tracked
instruments it names. No wall clock, no network, no environment, no working-tree
state, no git invocation on the build path. Every collection is sorted before
emission. A second build over an unchanged input set writes no byte, which is
INV-CTX-11 and is measured by `verify`.

SEPARATION OF PRODUCER FROM OBSERVER. This module WRITES and therefore may not
OBSERVE: it reads the declaration and the tracked instruments it names, and
nothing else — no git, no working tree, no clock, no environment. The Context
Closure Gate that measures uncommitted and branch state lives in
00-BOOK/tools/ukctx_gate.py, because measuring the working tree is an OBSERVATION
(UCKP-ART-13) and an observation may never reach a canonical artifact. Keeping
the two in one module would make this producer an undeclared reader of
WORKING_TREE under UCOS-UGA-001 OBS-INV-12 — which is exactly how the split was
found, by the gate refusing the first version of this file.

Commands:
    build     Emit the context root and every agent projection.
    plan      READ-ONLY: report what build WOULD write, and what would change.

Standard library only.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BOOK_DIR = os.path.dirname(HERE)
REPO = os.path.dirname(BOOK_DIR)

DECLARATION = os.path.join(BOOK_DIR, "DATA", "context-authority.json")
CAA = os.path.join(BOOK_DIR, "DATA", "constitutional-authority-alignment.json")
LAW = os.path.join(REPO, "engine", "uckp", "law.py")

GENERATED_BANNER = (
    "<!-- AUTO-GENERATED by 00-BOOK/tools/ukctx.py from 00-BOOK/DATA/context-authority.json.\n"
    "     DO NOT EDIT BY HAND. A hand edit is a drift failure (INV-CTX-07), not a new rule.\n"
    "     Regenerate with: python3 00-BOOK/tools/ukctx.py build -->"
)


# ---------------------------------------------------------------------------
# Primitives
# ---------------------------------------------------------------------------
def digest(text: str) -> str:
    """The one content digest. Canonical form is UTF-8 bytes (UCKP-ART-13)."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def load_json(path: str) -> dict:
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def read_text(path: str) -> str:
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def rel(path: str) -> str:
    return os.path.relpath(path, REPO).replace(os.sep, "/")


def exists(relpath: str) -> bool:
    return os.path.exists(os.path.join(REPO, relpath))


# ---------------------------------------------------------------------------
# Derivation from the named authorities — never restated, always read
# ---------------------------------------------------------------------------



def read_articles() -> list[dict]:
    """The articles of the root law, read from its only home.

    Restating an article here would be exactly the second authoring UCKP-ART-03
    voids, so the text is parsed out of engine/uckp/law.py rather than copied.

    Parsed with `ast`, not a regex over the source. The regex this replaced matched
    `Article("id", "title", "literal"...)` and therefore silently dropped UCKP-ART-01,
    whose text is the named constant SUPREMACY_CLAUSE: the law declares twenty articles
    and every agent surface carried nineteen, missing the one that establishes supremacy.
    A parser that understands names cannot lose an article for how it was spelled. This
    reads the module as text and never imports it — the law is authority, not a dependency.
    """
    tree = ast.parse(read_text(LAW))
    consts: dict[str, str] = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and isinstance(node.value, ast.Constant) \
                and isinstance(node.value.value, str):
            for tgt in node.targets:
                if isinstance(tgt, ast.Name):
                    consts[tgt.id] = node.value.value

    def literal(node) -> str | None:
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            return node.value
        if isinstance(node, ast.Name):
            return consts.get(node.id)
        return None

    out = []
    for node in ast.walk(tree):
        if not (isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
                and node.func.id == "Article" and len(node.args) >= 3):
            continue
        ident, title, text = (literal(a) for a in node.args[:3])
        if not (ident and title and text) or not ident.startswith("UCKP-ART-"):
            continue
        out.append({"id": ident, "title": title, "text": " ".join(text.split())})
    return sorted(out, key=lambda a: a["id"])


def read_authority_roles(caa: dict) -> list[dict]:
    roles = []
    for name, spec in sorted(caa.get("authority_roles", {}).items()):
        roles.append({
            "role": name,
            "may_hold_authority": bool(spec.get("may_hold_authority")),
            "cardinality": spec.get("cardinality", ""),
            "definition": spec.get("definition", ""),
        })
    return roles


def read_exclusion_classes() -> list[dict]:
    reg = load_json(os.path.join(BOOK_DIR, "DATA", "exclusion-register.json"))
    return [{"class": k, "definition": v} for k, v in sorted(reg.get("classes", {}).items())]


def read_mutation_authorities() -> list[dict]:
    mgb = load_json(os.path.join(BOOK_DIR, "DATA", "mutation-governance-boundary.json"))
    out = []
    for a in mgb.get("authorities", []):
        out.append({
            "authority": a.get("authority", ""),
            "implementation": a.get("implementation", ""),
            "enforcement": a.get("enforcement", ""),
        })
    return sorted(out, key=lambda a: a["authority"])


# NOTE — deliberately absent: a count of the generated-artifact registry.
# That register LISTS this generator's own 23 outputs, so quoting its size here
# would make the emitted bytes a function of a file that is itself a function of
# what was emitted. It converges (the register stores no digest of the output),
# but it is a self-referential edge with no purpose: every future generated
# artifact anywhere in the repository would rewrite every agent surface. The
# rule an agent needs is qualitative, not a tally, so the tally is not read.


# ---------------------------------------------------------------------------
# Emission
# ---------------------------------------------------------------------------
def md_table(headers: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(x.replace("|", "\\|") for x in r) + " |")
    return "\n".join(out)


def render_index(decl: dict, articles: list[dict], roles: list[dict]) -> str:
    root = decl["context_root"]
    L = [f"# {decl['title']}", "", GENERATED_BANNER, "",
         f"**Instrument:** `{rel(DECLARATION)}` · **Producer:** `{decl['producer']['home']}` · "
         f"**Root:** `{root['path']}`", "",
         "This root is a **generated projection layer**. It is not an authority and holds none. "
         "Every statement below is a view of an instrument that already says it; the instrument "
         "is named beside each domain.", "",
         "## The supreme authority", "",
         f"**{decl['constitutional_superior']['authority']}** — home `"
         f"{decl['constitutional_superior']['home']}`.", "",
         "Exactly one instrument holds role SUPREME. Every other instrument in the repository, "
         "including this one, derives from it and may not hold authority of its own.", "",
         "### Articles of the root law", "",
         md_table(["Article", "Title", "Statement"],
                  [[a["id"], a["title"], a["text"]] for a in articles]), "",
         "### Authority roles and their cardinality", "",
         md_table(["Role", "May hold authority", "Cardinality", "Definition"],
                  [[r["role"], "YES" if r["may_hold_authority"] else "no",
                    r["cardinality"], r["definition"]] for r in roles]), "",
         "## Context domains", "",
         "Each domain names the authority that **already** answers it. Under UCKP-ART-18 an "
         "existing canonical object is located and reused before anything is created, so this "
         "table declares no authority — it records where each one lives.", "",
         md_table(["Domain", "Authority", "Home", "Cardinality"],
                  [[d["domain"], d["authority"], f"`{d['authority_home']}`", d["cardinality"]]
                   for d in sorted(decl["domains"], key=lambda x: x["domain"])]), "",
         "### On the plural domains", "",
         "`certification`, `lifecycle` and the identity namespaces are **plural by design**. "
         "UCOS-CAA-001's model is that authority is single per **bounded question**, not per "
         "domain **name**, and each plural resolution carries its own `second_authority_test` "
         "proving that no two surfaces answer the same question. Collapsing them to one "
         "authority per name would destroy working governance rather than tighten it.", "",
         "## Relationship to UCXI-000001", "",
         f"`{decl['ucxi_relationship']['sibling']}` is the adjacent context instrument "
         f"(`{decl['ucxi_relationship']['sibling_home']}`). The two answer different bounded "
         "questions:", "",
         md_table(["Instrument", "Bounded question"],
                  [["UCXI-000001", decl["ucxi_relationship"]["QUESTION_ANSWERED_BY_UCXI"]],
                   ["UCOS-UCTX-001", decl["ucxi_relationship"]["QUESTION_ANSWERED_BY_UCTX"]]]), "",
         "Names that appear in both — "
         + ", ".join(f"`{k}`" for k in decl["ucxi_relationship"]["OVERLAP_SET"])
         + " — each carry a per-domain disambiguation naming UCXI's source and both answers. "
         "The collision set is recomputed from UCXI's own home on every run (INV-CTX-15), so a "
         "future collision fails until somebody states the difference.", "",
         "## Agent surfaces", "",
         "Every surface below is generated from this root. None is an authority; a hand edit to "
         "any of them is a drift failure under INV-CTX-07.", "",
         md_table(["Agent", "Surface", "Consumed by"],
                  [[a["agent"], f"`{a['surface']}`", a["consumed_by"]]
                   for a in sorted(decl["agent_surfaces"], key=lambda x: x["agent"])]), "",
         "## Invariants", "",
         md_table(["ID", "Name", "Fails closed"],
                  [[i["id"], i["name"], "YES" if i["fails_closed"] else "no"]
                   for i in decl["invariants"]]), "",
         "## Domain pages", "",
         ]
    for d in sorted(decl["domains"], key=lambda x: x["domain"]):
        L.append(f"- [{d['domain']}](./{d['domain']}.md) — {d['answers']}")
    L.append("")
    return "\n".join(L)


def render_domain(decl: dict, d: dict) -> str:
    L = [f"# Context domain: {d['domain']}", "", GENERATED_BANNER, "",
         md_table(["Property", "Value"],
                  [["Authority", d["authority"]],
                   ["Authority home", f"`{d['authority_home']}`"],
                   ["Cardinality", d["cardinality"]],
                   ["Constitutional binding", f"`{d['binding']}`"],
                   ["Declared by", f"`{rel(DECLARATION)}`"]]), "",
         "## The question this domain answers", "", d["answers"], "",
         "## Standing", "",
         f"This page is a projection. The authority is `{d['authority_home']}` and it is the only "
         "place the answer may change. Editing this page changes nothing except the drift "
         "measurement, which will then fail.", ""]
    if d["cardinality"] == "PLURAL_BY_DESIGN":
        L += ["## Why this domain is plural", "",
              "UCOS-CAA-001 declares this domain plural **by design**: authority here is single "
              "per bounded question, not per domain name. The binding named above carries the "
              "`second_authority_test` that proves no two surfaces answer the same question. "
              "This is a recorded finding, not a decision taken here.", ""]
    return "\n".join(L)


AGENT_PREAMBLE = (
    "You are working in the UCOS Ω∞ repository. This file is a GENERATED PROJECTION of "
    "`00-BOOK/DATA/context-authority.json`. It is not an authority and you may not edit it — "
    "a hand edit is a drift failure that `./verify.sh` will refuse (INV-CTX-07). To change what "
    "this file says, change the instrument it projects and regenerate."
)


def render_agent(decl: dict, surface: dict, articles: list[dict],
                 mut: list[dict], excl: list[dict]) -> str:
    sup = decl["constitutional_superior"]
    inv_ids = sorted(i["id"] for i in decl["invariants"])
    L = [f"# UCOS Ω∞ — repository context ({surface['agent']})", "",
         GENERATED_BANNER, "", AGENT_PREAMBLE, "",
         "## The one rule that explains every other one", "",
         f"There is exactly one supreme authority — **{sup['authority']}**, home "
         f"`{sup['home']}`. Everything else in this repository is a projection, a persistence "
         "mechanism, an execution environment or evidence. **None of those may hold authority "
         "of its own** (UCKP-ART-04). That includes this file, every document, every schema and "
         "every agent directory.", "",
         "Two consequences you will hit immediately:", "",
         "1. **Do not author knowledge that already exists.** UCKP-ART-18 requires you to locate "
         "the canonical object and reuse, extend or reference it. UCKP-ART-03 makes a second "
         "authoring of the same knowledge *void* — not discouraged, void.",
         "2. **Do not hand-edit generated output.** Every generated artifact is declared in "
         "`00-BOOK/DATA/generated-artifact-registry.json` with a producer, an input closure and "
         "a regeneration command. If a file you want to change is listed there, change its "
         "producer or its input and regenerate — never the file.", "",
         "## Where each answer lives", "",
         md_table(["If you need…", "Authority", "Home"],
                  [[d["answers"].split(".")[0].split("?")[0].strip(), d["authority"],
                    f"`{d['authority_home']}`"]
                   for d in sorted(decl["domains"], key=lambda x: x["domain"])]), "",
         "## Before you create a file", "",
         "Creating a tracked file is a **governed act**, not a free one:", "",
         "- Every tracked file becomes a UCOS-UGA-001 object and needs a Universal ID. Without "
         "one it is an *anonymous object* and `UGA-INV-01` fails.",
         "- Allocating that identity is **irreversible** and requires an operator-issued permit "
         "in `00-BOOK/DATA/allocation-permits.json`, bound to a manifest digest, a pre-image "
         "digest and a head. **You may not self-authorize it.**",
         "- A new `.json` carrying a top-level `authority` key must be bound in "
         "`00-BOOK/DATA/constitutional-authority-alignment.json` with a role and an article of "
         "derivation, or `CAA-INV-02` fails.",
         "- Preview with `python3 00-BOOK/tools/ukb.py build --plan` (read-only). Never run "
         "`--mint` without a permit.", "",
         "## Mutation authorities", "",
         "Each class of change answers to a different authority. These are not interchangeable:",
         "", md_table(["Authority", "Implementation", "Refusal"],
                      [[m["authority"], f"`{m['implementation']}`", m["enforcement"]]
                       for m in mut]), "",
         "## Excluded paths carry a declared class", "",
         "Adding a `.gitignore` rule does not remove an obligation — it adds one. Every ignored "
         "path must resolve to a class declared in `00-BOOK/DATA/exclusion-register.json`; an "
         "ignored path with no class is `ignored_unclassified` and fails closed.", "",
         md_table(["Class", "Meaning"], [[e["class"], e["definition"]] for e in excl]), "",
         "## Verification", "",
         "`./verify.sh` is the one repository-standard command.", "",
         md_table(["Command", "Claim"],
                  [["`./verify.sh --fast`", "developer feedback: lint + impact-selected tests"],
                   ["`./verify.sh` (`--change`)",
                    "commit validation: impact-selected tests + every governance gate"],
                   ["`./verify.sh --integration`",
                    "merge validation: whole suite under the floor + every gate"],
                   ["`./verify.sh --full`", "release certification; this is what CI runs"]]), "",
         # THE RANGE IS DERIVED, AND NAMES BOTH ENDS IN FULL. It used to read "INV-CTX-01..11"
         # with the last number typed in, so every new invariant made the sentence false and
         # the manifest template stale in the same edit. Both endpoints are now declared
         # invariant ids, which are corpus strings — so UFI normalises them to slots and the
         # reviewed template stops depending on how many invariants there happen to be.
         f"Context specifically: `python3 00-BOOK/tools/ukctx_gate.py` evaluates "
         f"{inv_ids[0]} through {inv_ids[-1]}. Regenerate context with "
         "`python3 00-BOOK/tools/ukctx.py build` — the generator and the gate are separate "
         "modules on purpose: the generator writes and never observes, the gate observes "
         "and never writes.",
         "", "## Articles of the root law", "",
         md_table(["Article", "Title", "Statement"],
                  [[a["id"], a["title"], a["text"]] for a in articles]), "",
         "## What you must never do", "", ]
    for ng in decl["non_goals"]:
        L.append(f"- {ng}")
    L += ["- Write context for yourself. Every agent surface in this repository is generated "
          "from one root; an agent-local rule is exactly the branch-local, unregistered, rival "
          "authority the constitution forbids.", ""]
    return "\n".join(L)


def render_mdc(body: str) -> str:
    """Cursor .mdc — YAML front matter, then the same body."""
    return ("---\n"
            "description: UCOS Ω∞ repository context (generated projection)\n"
            "alwaysApply: true\n"
            "---\n\n") + body


def render_readme(decl: dict) -> str:
    """README.md — the repository entry point, and NOTHING BUT POINTERS.

    A README is where a repository re-authors itself: it restates the law in friendlier
    words, lists the principles again, and becomes a second answer to questions the
    declarations already answer. UCKP-ART-03 makes that second authoring void, so this
    one states no rule, summarises no article and paraphrases no instrument. Every line
    below is either a command an operator types or a path to the object that holds the
    answer, and every one of those is READ FROM THE DECLARATION rather than typed here.

    IT IS NOT AN AGENT SURFACE. `AGENTS.md` is, and it carries the same body as every
    other agent projection — INV-CTX-13 measures that the surfaces do not diverge, so a
    bespoke rendering of one of them is a divergence by construction. The two files
    answer different questions: AGENTS.md is the context an agent is given, README.md is
    the door a human opens.
    """
    root = decl["context_root"]["path"]
    sup = decl["constitutional_superior"]
    surfaces = sorted(decl["agent_surfaces"], key=lambda s: s["agent"])
    lane = decl.get("proposal_lane", {})
    lines = [
        "# UCOS \u03a9\u221e",
        "",
        GENERATED_BANNER,
        "",
        "## Start here",
        "",
        "```bash",
        "./bootstrap.sh      # prepare the canonical environment",
        "./verify.sh --fast  # developer feedback",
        "./verify.sh         # commit validation",
        "```",
        "",
        f"`./verify.sh` is the one repository-standard command; `{rel(DECLARATION)}` "
        "declares what each mode claims.",
        "",
        "## Where the answers live",
        "",
        f"- Supreme authority — **{sup['authority']}**, `{sup['home']}`",
        f"- Context index — `{root}/00-CONTEXT-INDEX.md`, projected from "
        f"`{rel(DECLARATION)}`",
        f"- Bounded questions — one file per domain under `{root}/`",
        "",
        "## Agent surfaces",
        "",
        "The same context, projected to every agent that reads a different path:",
        "",
    ]
    lines += [f"- `{s['surface']}` — {s['consumed_by']}" for s in surfaces]
    if lane:
        lines += [
            "",
            "## Contributing",
            "",
            f"{lane['inbound']['description']}: `{lane['developer_path']}`. "
            f"{lane['boundary']}.",
            "",
            "```bash",
            "python3 00-BOOK/tools/ukctx_assimilate.py   # plan every discovered proposal",
            "```",
        ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------
def compute_outputs() -> tuple[dict, dict]:
    """(relpath -> content). Pure: no writes, no clock, no environment."""
    decl = load_json(DECLARATION)
    caa = load_json(CAA)
    articles = read_articles()
    roles = read_authority_roles(caa)
    mut = read_mutation_authorities()
    excl = read_exclusion_classes()

    root = decl["context_root"]["path"]
    out: dict[str, str] = {}
    out[f"{root}/00-CONTEXT-INDEX.md"] = render_index(decl, articles, roles)
    for d in sorted(decl["domains"], key=lambda x: x["domain"]):
        out[f"{root}/{d['domain']}.md"] = render_domain(decl, d)

    body = None
    for s in sorted(decl["agent_surfaces"], key=lambda x: x["agent"]):
        body = render_agent(decl, s, articles, mut, excl)
        out[s["surface"]] = render_mdc(body) if s["format"] == "mdc" else body

    # THE ENTRY POINT IS DECLARED, NOT ASSUMED. `entry_points` names the files a reader
    # arrives at, and each one says which producer emits it. AGENTS.md is NOT emitted
    # here: it is an agent surface, so the loop above already wrote it with the same body
    # every other surface carries, and writing it twice would be the divergence INV-CTX-13
    # refuses. An entry point that names a surface is a cross-reference, never a second
    # rendering.
    renderers = {"README.md": render_readme}
    for path, entry in sorted(decl.get("entry_points", {}).items()):
        if entry.get("surface_binding"):
            continue
        if path not in renderers:
            raise SystemExit(
                f"REFUSED — entry point {path!r} is declared but no renderer emits it, and "
                "it binds to no agent surface either. A declared entry point nothing writes "
                "is a promise of a file that will never exist.")
        out[path] = renderers[path](decl)

    # THE DECLARED CLOSURE IS THE MEASURED CLOSURE (D-R6). This list used to be
    # computed from every domain's authority_home, which produced 14 entries of which
    # 9 were never opened — a declaration wider than the derivation, which is the
    # "stale declaration is a false assurance" defect UGA OBS-INV-12 polices elsewhere.
    # The set now comes from `true_input_set`, which was established by runtime tracing
    # (sys.addaudithook over `open`, cold start, outputs removed) rather than by reading
    # this file. A domain's authority_home is EXISTENCE-CHECKED by INV-CTX-02; being
    # checked for existence is not being read, and only what is read is an input.
    inputs = sorted(decl["true_input_set"]["inputs"])

    manifest = {
        "artifact_id": "UCOS-UCTX-MANIFEST-001",
        "title": ("Context Projection Manifest — every emitted surface, its digest "
                  "and its derivation"),
        "authority": ("NONE — DERIVED TRUTH. A measurement of what the producer "
                      "emitted. It records and asserts nothing."),
        "producer": decl["producer"]["home"],
        "declaration": rel(DECLARATION),
        "derives_from": inputs,
        "projections": [
            {"path": p, "sha256": digest(out[p]), "bytes": len(out[p].encode("utf-8")),
             "derives_from": inputs}
            for p in sorted(out)
        ],
    }
    out[f"{root}/MANIFEST.json"] = json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"
    return out, decl


def write_outputs(out: dict) -> list[str]:
    changed = []
    for relpath in sorted(out):
        full = os.path.join(REPO, relpath)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        new = out[relpath]
        old = read_text(full) if os.path.isfile(full) else None
        if old != new:
            with open(full, "w", encoding="utf-8") as fh:
                fh.write(new)
            changed.append(relpath)
    return changed


def cmd_build(_args) -> int:
    out, _ = compute_outputs()
    changed = write_outputs(out)
    print(f"UCOS-UCTX-001 context build — {len(out)} projections")
    for c in changed:
        print(f"  wrote {c}")
    if not changed:
        print("  no change (fixed point)")
    return 0


def cmd_plan(_args) -> int:
    out, _ = compute_outputs()
    print(f"UCOS-UCTX-001 context plan — {len(out)} projections (READ-ONLY, nothing written)")
    n = 0
    for relpath in sorted(out):
        full = os.path.join(REPO, relpath)
        old = read_text(full) if os.path.isfile(full) else None
        state = "NEW" if old is None else ("CHANGED" if old != out[relpath] else "current")
        if state != "current":
            n += 1
        print(f"  [{state:8}] {relpath}")
    print(f"would write {n} file(s)")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        prog="ukctx.py",
        description="UCOS-UCTX-001 — Universal Context Generator. "
                    "The Context Closure Gate lives in 00-BOOK/tools/ukctx_gate.py.")
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("build", help="Emit the context root and every agent projection.")
    sub.add_parser("plan", help="READ-ONLY: report what build would write.")
    args = ap.parse_args(argv)
    return {"build": cmd_build, "plan": cmd_plan}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
